using FarmingApi.Modules.Financials.GLAccountDetermination;
using FarmingApi.Modules.Financials.JournalEntry;
using BPEntity = FarmingApi.Modules.BusinessPartners.BusinessPartnersMaster.BusinessPartnersMaster;

namespace FarmingApi.Modules.PurchaseAP.GoodsReceiptPO;

public interface IGoodsReceiptPOJournalService
{
    JournalEntry CreateJournalEntry(GoodsReceiptPO receipt, BPEntity vendor);
}

public class GoodsReceiptPOJournalService : IGoodsReceiptPOJournalService
{
    private readonly MyDbContext _db;

    public GoodsReceiptPOJournalService(MyDbContext db)
    {
        _db = db;
    }

    public JournalEntry CreateJournalEntry(GoodsReceiptPO receipt, BPEntity vendor)
    {
        var gl = _db.Set<GLAccountDetermination>().FirstOrDefault()
                 ?? throw new InvalidOperationException(
                     "GL Account Determination (KGLD) not configured. " +
                     "Go to Administration → GL Account Determination and add " +
                     "InventoryAccount and InventoryOffset.");

        var inventoryCode = gl.InventoryAccount;
        var offsetCode    = gl.InventoryOffset;

        if (string.IsNullOrWhiteSpace(inventoryCode))
            throw new InvalidOperationException(
                "Inventory account not set in GL Account Determination (KGLD).");
        if (string.IsNullOrWhiteSpace(offsetCode))
            throw new InvalidOperationException(
                "Inventory Offset (GR/IR clearing) account not set in GL Account Determination (KGLD).");

        // A Goods Receipt PO capitalises the goods at cost (net of tax).
        // Tax is not recognised here — it is posted when the AP invoice arrives.
        var goodsValue = receipt.Total - receipt.TaxAmount;

        if (goodsValue <= 0)
            throw new InvalidOperationException(
                $"Cannot post Goods Receipt PO {receipt.DocNum}: goods value is {goodsValue}");

        var postingDate = receipt.PostingDate ?? receipt.DocDate ?? DateTime.UtcNow;

        var je = new JournalEntry
        {
            JrnlNo          = GenerateJournalNumber(),
            TransDate       = postingDate,
            DueDate         = postingDate,
            DocDate         = receipt.DocDate ?? postingDate,
            RefNo           = receipt.DocNum,
            Memo            = $"Goods Receipt PO {receipt.DocNum} - {vendor.CardName}",
            TransType       = "GRPO",
            BaseDocEntry    = receipt.Id,
            BaseDocType     = "KGRP",
            Currency        = "USD",
            ExchangeRate    = 1,
            TotalDebit      = 0,
            TotalCredit     = 0,
            TotalFC         = 0,
            TotalLC         = 0,
            Status          = "O",
            IsAutoGenerated = true,
            VersionNum      = 1,
            CreatedAt       = DateTime.UtcNow,
            InActive        = false,
        };

        int lineNum = 1;

        // Dr Inventory — goods received into stock, at cost
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = inventoryCode,
            AccountName = "Inventory",
            CardCode    = null,
            CardName    = null,
            Debit       = goodsValue,
            Credit      = 0,
            DebitLC     = goodsValue,
            CreditLC    = 0,
            DebitFC     = 0,
            CreditFC    = 0,
            LineMemo    = $"Inventory received — {receipt.DocNum}",
            TaxAmount   = 0,
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        // Cr Inventory Offset — GR/IR clearing (goods received, not yet invoiced)
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = offsetCode,
            AccountName = "GR/IR Clearing",
            CardCode    = vendor.Code,
            CardName    = vendor.CardName,
            Debit       = 0,
            Credit      = goodsValue,
            DebitLC     = 0,
            CreditLC    = goodsValue,
            DebitFC     = 0,
            CreditFC    = 0,
            LineMemo    = $"GR/IR clearing — {receipt.DocNum}",
            TaxAmount   = 0,
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        var totalDr = je.Lines.Sum(l => l.Debit);
        var totalCr = je.Lines.Sum(l => l.Credit);
        if (Math.Abs(totalDr - totalCr) > 0.01m)
            throw new InvalidOperationException(
                $"Journal entry unbalanced: Dr={totalDr:N2} Cr={totalCr:N2} for {receipt.DocNum}.");

        je.TotalDebit  = totalDr;
        je.TotalCredit = totalCr;
        je.TotalLC     = totalDr;
        je.TotalFC     = 0;

        _db.Set<JournalEntry>().Add(je);
        return je;
    }

    private string GenerateJournalNumber()
    {
        var year   = DateTime.Now.Year;
        var prefix = $"JE-{year}-";

        var last = _db.Set<JournalEntry>()
            .Where(j => j.JrnlNo.StartsWith(prefix))
            .OrderByDescending(j => j.Id)
            .FirstOrDefault();

        if (last == null)
            return $"{prefix}00001";

        var parts = last.JrnlNo.Split('-');
        if (parts.Length >= 3 && int.TryParse(parts[2], out int lastNum))
            return $"{prefix}{(lastNum + 1):D5}";

        return $"{prefix}00001";
    }
}
