namespace FarmingApi.Modules.InventoryManagement.InventoryJournal;

// Read-only — rows are system-generated by IInventoryPostingService,
// never created or edited directly through the API.
public class InventoryJournalResponse
{
    public int      Id           { get; set; }
    public string   ItemCode     { get; set; } = null!;
    public string   WhsCode      { get; set; } = null!;
    public DateTime PostingDate  { get; set; }
    public string   TransType    { get; set; } = null!;
    public string   BaseDocType  { get; set; } = null!;
    public int      BaseDocEntry { get; set; }
    public string?  BaseDocNum   { get; set; }
    public string?  CardCode     { get; set; }
    public string?  CardName     { get; set; }
    public decimal  InQty        { get; set; }
    public decimal  OutQty       { get; set; }
    public decimal  UnitCost     { get; set; }
    public decimal  TransValue   { get; set; }
    public decimal  QtyBalance   { get; set; }
    public decimal  ValueBalance { get; set; }
    public DateTime CreatedAt    { get; set; }
}
