using FarmingApi.Modules.Financials.GLAccountDetermination;
using FarmingApi.Modules.Financials.JournalEntry;
using BPEntity = FarmingApi.Modules.BusinessPartners.BusinessPartnersMaster.BusinessPartnersMaster;

namespace FarmingApi.Modules.PurchaseAP.APDownPaymentInvoice;

public interface IAPDownPaymentInvoiceJournalService
{
    JournalEntry CreateJournalEntry(APDownPaymentInvoice downPaymentInvoice, BPEntity vendor);
}

public class APDownPaymentInvoiceJournalService : IAPDownPaymentInvoiceJournalService
{
    private readonly MyDbContext _db;

    public APDownPaymentInvoiceJournalService(MyDbContext db)
    {
        _db = db;
    }

    public JournalEntry CreateJournalEntry(APDownPaymentInvoice downPaymentInvoice, BPEntity vendor)
    {
        var gl = _db.Set<GLAccountDetermination>().FirstOrDefault()
                 ?? throw new InvalidOperationException(
                     "GL Account Determination (KGLD) not configured. " +
                     "Go to Administration → GL Account Determination and add " +
                     "AccountsPayable and VendorDeposit.");

        var payableCode = gl.AccountsPayable;
        var depositCode = gl.VendorDeposit;

        if (string.IsNullOrWhiteSpace(payableCode))
            throw new InvalidOperationException(
                "Accounts Payable account not set in GL Account Determination (KGLD).");
        if (string.IsNullOrWhiteSpace(depositCode))
            throw new InvalidOperationException(
                "Vendor Deposit (down payment paid) account not set in GL Account Determination (KGLD).");

        var grandTotal = downPaymentInvoice.Total;

        if (grandTotal <= 0)
            throw new InvalidOperationException(
                $"Cannot post AP Down Payment Invoice {downPaymentInvoice.DocNum}: total is {grandTotal}");

        var postingDate = downPaymentInvoice.PostingDate ?? DateTime.UtcNow;

        var je = new JournalEntry
        {
            JrnlNo          = GenerateJournalNumber(),
            TransDate       = postingDate,
            DueDate         = downPaymentInvoice.DueDate ?? postingDate,
            DocDate         = postingDate,
            RefNo           = downPaymentInvoice.DocNum,
            Memo            = $"AP Down Payment Invoice {downPaymentInvoice.DocNum} - {vendor.CardName}",
            TransType       = "APDP",
            BaseDocEntry    = downPaymentInvoice.Id,
            BaseDocType     = "KPDI",
            Currency        = "USD",
            ExchangeRate    = 1,
            TotalDebit      = 0,
            TotalCredit     = 0,
            TotalFC         = 0,
            TotalLC         = 0,
            Status          = "O",
            IsAutoGenerated = true,
            VersionNum      = 1,
            CreatedAt       = DateTime.UtcNow,
            InActive        = false,
        };

        int lineNum = 1;

        // A down payment to a vendor is recognised as a prepayment asset, and
        // raises a payable for the amount now due to the vendor.
        // Dr Vendor Deposit — the prepayment asset
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = depositCode,
            AccountName = "Vendor Down Payment",
            CardCode    = vendor.Code,
            CardName    = vendor.CardName,
            Debit       = grandTotal,
            Credit      = 0,
            DebitLC     = grandTotal,
            CreditLC    = 0,
            DebitFC     = 0,
            CreditFC    = 0,
            LineMemo    = $"Vendor down payment — {downPaymentInvoice.DocNum}",
            TaxAmount   = 0,
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        // Cr Accounts Payable — amount now owed to the vendor
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = payableCode,
            AccountName = "Accounts Payable",
            CardCode    = vendor.Code,
            CardName    = vendor.CardName,
            Debit       = 0,
            Credit      = grandTotal,
            DebitLC     = 0,
            CreditLC    = grandTotal,
            DebitFC     = 0,
            CreditFC    = 0,
            LineMemo    = $"Accounts Payable — {downPaymentInvoice.DocNum}",
            TaxAmount   = 0,
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        var totalDr = je.Lines.Sum(l => l.Debit);
        var totalCr = je.Lines.Sum(l => l.Credit);
        if (Math.Abs(totalDr - totalCr) > 0.01m)
            throw new InvalidOperationException(
                $"Journal entry unbalanced: Dr={totalDr:N2} Cr={totalCr:N2} for {downPaymentInvoice.DocNum}.");

        je.TotalDebit  = totalDr;
        je.TotalCredit = totalCr;
        je.TotalLC     = totalDr;
        je.TotalFC     = 0;

        _db.Set<JournalEntry>().Add(je);
        return je;
    }

    private string GenerateJournalNumber()
    {
        var year   = DateTime.Now.Year;
        var prefix = $"JE-{year}-";

        var last = _db.Set<JournalEntry>()
            .Where(j => j.JrnlNo.StartsWith(prefix))
            .OrderByDescending(j => j.Id)
            .FirstOrDefault();

        if (last == null)
            return $"{prefix}00001";

        var parts = last.JrnlNo.Split('-');
        if (parts.Length >= 3 && int.TryParse(parts[2], out int lastNum))
            return $"{prefix}{(lastNum + 1):D5}";

        return $"{prefix}00001";
    }
}
