using AutoMapper;
using FarmingApi.Modules.Master.BusinessPartner;

namespace FarmingApi.Modules.SaleAR.ARInvoice;

public class ARInvoiceMapper : Profile
{
    public ARInvoiceMapper()
    {
        // ─────────────────────────────────────────
        // ARInvoice → ListResponse  (grid/table)
        // ─────────────────────────────────────────
        CreateMap<ARInvoice, ARInvoiceListResponse>()
            .ForMember(dest => dest.BPCode,
                opt => opt.MapFrom(src => src.BusinessPartner.Code))
            .ForMember(dest => dest.BPName,
                opt => opt.MapFrom(src => src.BPName))
            .ForMember(dest => dest.Status,
                opt => opt.MapFrom(src => src.Status.ToString()));

        // ─────────────────────────────────────────
        // ARInvoice → DetailResponse  (single view)
        // ─────────────────────────────────────────
        CreateMap<ARInvoice, ARInvoiceDetailResponse>()
            .ForMember(dest => dest.BPCode,
                opt => opt.MapFrom(src => src.BusinessPartner.Code))
            .ForMember(dest => dest.Status,
                opt => opt.MapFrom(src => src.Status.ToString()))
            .ForMember(dest => dest.Lines,
                opt => opt.MapFrom(src => src.Lines));

        // ─────────────────────────────────────────
        // ARInvoiceLine → LineResponse
        // ─────────────────────────────────────────
        CreateMap<ARInvoiceLine, ARInvoiceLineResponse>()
            .ForMember(dest => dest.ItemType,
                opt => opt.MapFrom(src => src.ItemType.ToString()));

        // ─────────────────────────────────────────
        // CreateRequest → ARInvoice
        // ─────────────────────────────────────────
        CreateMap<ARInvoiceCreateRequest, ARInvoice>()
            .ForMember(dest => dest.Id,
                opt => opt.Ignore())
            .ForMember(dest => dest.DocNumber,
                opt => opt.Ignore())          // generated by service
            .ForMember(dest => dest.Status,
                opt => opt.Ignore())          // defaults to Open
            .ForMember(dest => dest.BPName,
                opt => opt.Ignore())          // filled from BP lookup in service
            .ForMember(dest => dest.BusinessPartner,
                opt => opt.Ignore())          // navigation — EF handles
            .ForMember(dest => dest.TotalBeforeDiscount,
                opt => opt.Ignore())          // calculated in service
            .ForMember(dest => dest.DiscountAmount,
                opt => opt.Ignore())
            .ForMember(dest => dest.TaxTotal,
                opt => opt.Ignore())
            .ForMember(dest => dest.GrandTotal,
                opt => opt.Ignore())
            .ForMember(dest => dest.BalanceDue,
                opt => opt.Ignore())
            .ForMember(dest => dest.AppliedAmount,
                opt => opt.Ignore())
            .ForMember(dest => dest.Lines,
                opt => opt.MapFrom(src => src.Lines));

        // ─────────────────────────────────────────
        // LineRequest → ARInvoiceLine
        // ─────────────────────────────────────────
        CreateMap<ARInvoiceLineRequest, ARInvoiceLine>()
            .ForMember(dest => dest.Id,
                opt => opt.Ignore())
            .ForMember(dest => dest.ARInvoiceId,
                opt => opt.Ignore())
            .ForMember(dest => dest.ARInvoice,
                opt => opt.Ignore())
            .ForMember(dest => dest.VatRate,
                opt => opt.Ignore())          // resolved from VatCode in service
            .ForMember(dest => dest.LineTotal,
                opt => opt.Ignore())          // calculated in service
            .ForMember(dest => dest.TaxAmount,
                opt => opt.Ignore())          // calculated in service
            .ForMember(dest => dest.ItemType,
                opt => opt.MapFrom(src =>
                    src.ItemType == "Service"
                        ? LineItemType.Service
                        : LineItemType.Item));

        // ─────────────────────────────────────────
        // UpdateRequest → ARInvoice
        // ─────────────────────────────────────────
        CreateMap<ARInvoiceUpdateRequest, ARInvoice>()
            .ForMember(dest => dest.Id,
                opt => opt.Ignore())
            .ForMember(dest => dest.DocNumber,
                opt => opt.Ignore())
            .ForMember(dest => dest.DocSeries,
                opt => opt.Ignore())
            .ForMember(dest => dest.Status,
                opt => opt.Ignore())
            .ForMember(dest => dest.BusinessPartnerId,
                opt => opt.Ignore())          // BP cannot change on update
            .ForMember(dest => dest.BusinessPartner,
                opt => opt.Ignore())
            .ForMember(dest => dest.BPName,
                opt => opt.Ignore())
            .ForMember(dest => dest.TotalBeforeDiscount,
                opt => opt.Ignore())
            .ForMember(dest => dest.DiscountAmount,
                opt => opt.Ignore())
            .ForMember(dest => dest.TaxTotal,
                opt => opt.Ignore())
            .ForMember(dest => dest.GrandTotal,
                opt => opt.Ignore())
            .ForMember(dest => dest.BalanceDue,
                opt => opt.Ignore())
            .ForMember(dest => dest.AppliedAmount,
                opt => opt.Ignore())
            .ForMember(dest => dest.Lines,
                opt => opt.MapFrom(src => src.Lines));
    }
}