using FarmingApi.Modules.Financials.GLAccountDetermination;
using FarmingApi.Modules.Financials.JournalEntry;
using FarmingApi.Modules.Inventory.ItemsMaster;

namespace FarmingApi.Modules.SaleAR.Delivery;
public interface IDeliveryJournalService
{
    JournalEntry? CreateJournalEntry(Delivery delivery);
}
public class DeliveryJournalService : IDeliveryJournalService
{
    private readonly MyDbContext _db;

    public DeliveryJournalService(MyDbContext db) => _db = db;

    public JournalEntry? CreateJournalEntry(Delivery delivery)
    {
        // ── Posting basis: item cost, else fall back to sales value ──
        // Preferred basis is the item's cost (ItemCost → PurchasePrice). When an
        // item has no cost set, fall back to the line's sales amount so the
        // delivery still posts a JE (flagged in the memo so it's transparent).
        var itemIds = delivery.Items.Select(l => l.ItemId).Distinct().ToList();
        var costById = _db.Set<ItemsMaster>()
            .Where(i => itemIds.Contains(i.Id))
            .ToDictionary(i => i.Id, i => i.ItemCost > 0 ? i.ItemCost : i.PurchasePrice);

        bool usedSalesFallback = false;
        decimal totalCost = delivery.Items.Sum(l =>
        {
            var cost = costById.TryGetValue(l.ItemId, out var c) ? c : 0m;
            if (cost > 0) return cost * l.Quantity;
            usedSalesFallback = true;
            return l.Total;   // sales value of the line
        });

        // Genuinely empty delivery (no cost and no value) — nothing to post.
        if (totalCost <= 0)
            return null;

        // ── Accounts from KGLD ────────────────────────────────────
        var gl = _db.Set<GLAccountDetermination>().FirstOrDefault()
            ?? throw new InvalidOperationException(
                "GL Account Determination (KGLD) is not configured. " +
                "Set the Inventory and Cost of Goods Sold accounts first.");

        var cogsCode = gl.CostOfGoodsSold;
        var invCode  = gl.InventoryAccount;

        if (string.IsNullOrWhiteSpace(cogsCode))
            throw new InvalidOperationException(
                "Cost of Goods Sold account is not set in GL Account Determination (KGLD).");
        if (string.IsNullOrWhiteSpace(invCode))
            throw new InvalidOperationException(
                "Inventory account is not set in GL Account Determination (KGLD).");

        var postingDate = delivery.PostingDate ?? DateTime.UtcNow;

        var je = new JournalEntry
        {
            JrnlNo          = GenerateJournalNumber(),
            TransDate       = postingDate,
            DueDate         = delivery.DeliveryDate ?? postingDate,
            DocDate         = postingDate,
            RefNo           = delivery.DocNum,
            Memo            = $"Delivery {delivery.DocNum} — goods issued"
                              + (usedSalesFallback ? " (posted at sales value — set item costs for accurate COGS)" : ""),
            TransType       = "DLN",
            BaseDocType     = "KADV",
            BaseDocEntry    = delivery.Id,
            Currency        = "USD",
            ExchangeRate    = 1,
            Status          = "O",
            IsAutoGenerated = true,
            VersionNum      = 1,
            CreatedAt       = DateTime.UtcNow,
            InActive        = false,
        };

        int lineNum = 1;

        // DR: Cost of Goods Sold
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = cogsCode!,
            AccountName = "Cost of Goods Sold",
            Debit       = totalCost,
            Credit      = 0,
            DebitLC     = totalCost,
            CreditLC    = 0,
            LineMemo    = $"COGS — {delivery.DocNum}",
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        // CR: Inventory
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = invCode!,
            AccountName = "Inventory",
            Debit       = 0,
            Credit      = totalCost,
            DebitLC     = 0,
            CreditLC    = totalCost,
            LineMemo    = $"Inventory issued — {delivery.DocNum}",
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        var totalDr = je.Lines.Sum(l => l.Debit);
        var totalCr = je.Lines.Sum(l => l.Credit);
        if (Math.Abs(totalDr - totalCr) > 0.01m)
            throw new InvalidOperationException(
                $"Journal entry unbalanced: Dr={totalDr:N2} Cr={totalCr:N2}.");

        je.TotalDebit  = totalDr;
        je.TotalCredit = totalCr;
        je.TotalLC     = totalDr;
        je.TotalFC     = totalDr;

        _db.Set<JournalEntry>().Add(je);
        return je;
    }

    private string GenerateJournalNumber()
    {
        var year   = DateTime.Now.Year;
        var prefix = $"JE-{year}-";

        var last = _db.Set<JournalEntry>()
            .Where(j => j.JrnlNo.StartsWith(prefix))
            .OrderByDescending(j => j.Id)
            .FirstOrDefault();

        if (last == null) return $"{prefix}00001";

        var parts = last.JrnlNo.Split('-');
        if (parts.Length >= 3 && int.TryParse(parts[2], out int lastNum))
            return $"{prefix}{(lastNum + 1):D5}";

        return $"{prefix}00001";
    }
}
