using FarmingApi.Modules.Financials.GLAccountDetermination;
using FarmingApi.Modules.Financials.JournalEntry;
using BPEntity = FarmingApi.Modules.BusinessPartners.BusinessPartnersMaster.BusinessPartnersMaster;

namespace FarmingApi.Modules.PurchaseAP.GoodsReturn;

public interface IGoodsReturnJournalService
{
    JournalEntry CreateJournalEntry(GoodsReturn goodsReturn, BPEntity vendor);
}

public class GoodsReturnJournalService : IGoodsReturnJournalService
{
    private readonly MyDbContext _db;

    public GoodsReturnJournalService(MyDbContext db)
    {
        _db = db;
    }

    public JournalEntry CreateJournalEntry(GoodsReturn goodsReturn, BPEntity vendor)
    {
        var gl = _db.Set<GLAccountDetermination>().FirstOrDefault()
                 ?? throw new InvalidOperationException(
                     "GL Account Determination (KGLD) not configured. " +
                     "Go to Administration → GL Account Determination and add " +
                     "InventoryAccount and InventoryOffset.");

        var inventoryCode = gl.InventoryAccount;
        var offsetCode    = gl.InventoryOffset;

        if (string.IsNullOrWhiteSpace(inventoryCode))
            throw new InvalidOperationException(
                "Inventory account not set in GL Account Determination (KGLD).");
        if (string.IsNullOrWhiteSpace(offsetCode))
            throw new InvalidOperationException(
                "Inventory Offset (GR/IR clearing) account not set in GL Account Determination (KGLD).");

        // A Goods Return reverses a Goods Receipt PO: stock leaves inventory and
        // the GR/IR clearing accrual is reversed. Valued at cost (no tax here).
        var goodsValue = goodsReturn.Total;

        if (goodsValue <= 0)
            throw new InvalidOperationException(
                $"Cannot post Goods Return {goodsReturn.DocNum}: goods value is {goodsValue}");

        var postingDate = goodsReturn.PostingDate ?? DateTime.UtcNow;

        var je = new JournalEntry
        {
            JrnlNo          = GenerateJournalNumber(),
            TransDate       = postingDate,
            DueDate         = postingDate,
            DocDate         = postingDate,
            RefNo           = goodsReturn.DocNum,
            Memo            = $"Goods Return {goodsReturn.DocNum} - {vendor.CardName}",
            TransType       = "GRTN",
            BaseDocEntry    = goodsReturn.Id,
            BaseDocType     = "KGRT",
            Currency        = "USD",
            ExchangeRate    = 1,
            TotalDebit      = 0,
            TotalCredit     = 0,
            TotalFC         = 0,
            TotalLC         = 0,
            Status          = "O",
            IsAutoGenerated = true,
            VersionNum      = 1,
            CreatedAt       = DateTime.UtcNow,
            InActive        = false,
        };

        int lineNum = 1;

        // Dr Inventory Offset — reverse the GR/IR clearing accrual
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = offsetCode,
            AccountName = "GR/IR Clearing",
            CardCode    = vendor.Code,
            CardName    = vendor.CardName,
            Debit       = goodsValue,
            Credit      = 0,
            DebitLC     = goodsValue,
            CreditLC    = 0,
            DebitFC     = 0,
            CreditFC    = 0,
            LineMemo    = $"GR/IR clearing reversal — {goodsReturn.DocNum}",
            TaxAmount   = 0,
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        // Cr Inventory — goods returned to vendor, leave stock at cost
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = inventoryCode,
            AccountName = "Inventory",
            CardCode    = null,
            CardName    = null,
            Debit       = 0,
            Credit      = goodsValue,
            DebitLC     = 0,
            CreditLC    = goodsValue,
            DebitFC     = 0,
            CreditFC    = 0,
            LineMemo    = $"Inventory returned — {goodsReturn.DocNum}",
            TaxAmount   = 0,
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        var totalDr = je.Lines.Sum(l => l.Debit);
        var totalCr = je.Lines.Sum(l => l.Credit);
        if (Math.Abs(totalDr - totalCr) > 0.01m)
            throw new InvalidOperationException(
                $"Journal entry unbalanced: Dr={totalDr:N2} Cr={totalCr:N2} for {goodsReturn.DocNum}.");

        je.TotalDebit  = totalDr;
        je.TotalCredit = totalCr;
        je.TotalLC     = totalDr;
        je.TotalFC     = 0;

        _db.Set<JournalEntry>().Add(je);
        return je;
    }

    private string GenerateJournalNumber()
    {
        var year   = DateTime.Now.Year;
        var prefix = $"JE-{year}-";

        var last = _db.Set<JournalEntry>()
            .Where(j => j.JrnlNo.StartsWith(prefix))
            .OrderByDescending(j => j.Id)
            .FirstOrDefault();

        if (last == null)
            return $"{prefix}00001";

        var parts = last.JrnlNo.Split('-');
        if (parts.Length >= 3 && int.TryParse(parts[2], out int lastNum))
            return $"{prefix}{(lastNum + 1):D5}";

        return $"{prefix}00001";
    }
}
