using FarmingApi.Modules.Financials.GLAccountDetermination;
using FarmingApi.Modules.Financials.JournalEntry;
using BPEntity = FarmingApi.Modules.BusinessPartners.BusinessPartnersMaster.BusinessPartnersMaster;

namespace FarmingApi.Modules.PurchaseAP.APCreditNote;

public interface IAPCreditNoteJournalService
{
    JournalEntry CreateJournalEntry(APCreditNote creditNote, BPEntity vendor);
}

public class APCreditNoteJournalService : IAPCreditNoteJournalService
{
    private readonly MyDbContext _db;

    public APCreditNoteJournalService(MyDbContext db)
    {
        _db = db;
    }

    public JournalEntry CreateJournalEntry(APCreditNote creditNote, BPEntity vendor)
    {
        var gl = _db.Set<GLAccountDetermination>().FirstOrDefault()
                 ?? throw new InvalidOperationException(
                     "GL Account Determination (KGLD) not configured. " +
                     "Go to Administration → GL Account Determination and add " +
                     "AccountsPayable, PurchaseExpense, PurchaseTax.");

        var payableCode = gl.AccountsPayable;
        var expenseCode = gl.PurchaseExpense;
        var taxCode     = gl.PurchaseTax;

        if (string.IsNullOrWhiteSpace(payableCode))
            throw new InvalidOperationException(
                "Accounts Payable account not set in GL Account Determination (KGLD).");
        if (string.IsNullOrWhiteSpace(expenseCode))
            throw new InvalidOperationException(
                "Purchase Expense account not set in GL Account Determination (KGLD).");

        var grandTotal = creditNote.Total;
        var taxAmount  = creditNote.TaxAmount;
        var netExpense = grandTotal - taxAmount;

        if (grandTotal <= 0)
            throw new InvalidOperationException(
                $"Cannot post AP Credit Note {creditNote.DocNum}: total is {grandTotal}");

        var postingDate = creditNote.PostingDate ?? DateTime.UtcNow;

        var je = new JournalEntry
        {
            JrnlNo          = GenerateJournalNumber(),
            TransDate       = postingDate,
            DueDate         = creditNote.DueDate ?? postingDate,
            DocDate         = postingDate,
            RefNo           = creditNote.DocNum,
            Memo            = $"AP Credit Note {creditNote.DocNum} - {vendor.CardName}",
            TransType       = "APCN",
            BaseDocEntry    = creditNote.Id,
            BaseDocType     = "KPCN",
            Currency        = "USD",
            ExchangeRate    = 1,
            TotalDebit      = 0,
            TotalCredit     = 0,
            TotalFC         = 0,
            TotalLC         = 0,
            Status          = "O",
            IsAutoGenerated = true,
            VersionNum      = 1,
            CreatedAt       = DateTime.UtcNow,
            InActive        = false,
        };

        int lineNum = 1;

        // An AP credit note REVERSES the AP invoice: it reduces the payable and the expense.
        // Dr Accounts Payable — reduce what we owe the vendor (full amount incl. tax)
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = payableCode,
            AccountName = "Accounts Payable",
            CardCode    = vendor.Code,
            CardName    = vendor.CardName,
            Debit       = grandTotal,
            Credit      = 0,
            DebitLC     = grandTotal,
            CreditLC    = 0,
            DebitFC     = 0,
            CreditFC    = 0,
            LineMemo    = $"Accounts Payable — {creditNote.DocNum}",
            TaxAmount   = 0,
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        // Cr Purchase Expense — net of tax
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = expenseCode,
            AccountName = "Purchase Expense",
            CardCode    = null,
            CardName    = null,
            Debit       = 0,
            Credit      = netExpense,
            DebitLC     = 0,
            CreditLC    = netExpense,
            DebitFC     = 0,
            CreditFC    = 0,
            LineMemo    = $"Purchase return — {creditNote.DocNum}",
            TaxAmount   = 0,
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        // Cr Input VAT — reverse the tax, only when there is tax
        if (taxAmount > 0)
        {
            if (string.IsNullOrWhiteSpace(taxCode))
                throw new InvalidOperationException(
                    "Credit note has tax but Purchase Tax (input VAT) account is not set in KGLD.");

            je.Lines.Add(new JournalEntryLine
            {
                LineNum     = lineNum++,
                AccountCode = taxCode,
                AccountName = "Input VAT",
                CardCode    = null,
                CardName    = null,
                Debit       = 0,
                Credit      = taxAmount,
                DebitLC     = 0,
                CreditLC    = taxAmount,
                DebitFC     = 0,
                CreditFC    = 0,
                LineMemo    = $"Input VAT reversal — {creditNote.DocNum}",
                TaxAmount   = taxAmount,
                CreatedAt   = DateTime.UtcNow,
                InActive    = false,
            });
        }

        var totalDr = je.Lines.Sum(l => l.Debit);
        var totalCr = je.Lines.Sum(l => l.Credit);
        if (Math.Abs(totalDr - totalCr) > 0.01m)
            throw new InvalidOperationException(
                $"Journal entry unbalanced: Dr={totalDr:N2} Cr={totalCr:N2}. " +
                $"Check credit note Total ({grandTotal}) vs TaxAmount ({taxAmount}).");

        je.TotalDebit  = totalDr;
        je.TotalCredit = totalCr;
        je.TotalLC     = totalDr;
        je.TotalFC     = 0;

        _db.Set<JournalEntry>().Add(je);
        return je;
    }

    private string GenerateJournalNumber()
    {
        var year   = DateTime.Now.Year;
        var prefix = $"JE-{year}-";

        var last = _db.Set<JournalEntry>()
            .Where(j => j.JrnlNo.StartsWith(prefix))
            .OrderByDescending(j => j.Id)
            .FirstOrDefault();

        if (last == null)
            return $"{prefix}00001";

        var parts = last.JrnlNo.Split('-');
        if (parts.Length >= 3 && int.TryParse(parts[2], out int lastNum))
            return $"{prefix}{(lastNum + 1):D5}";

        return $"{prefix}00001";
    }
}
