using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FarmingApi.Core;

namespace FarmingApi.Modules.Financials.JournalEntry;

public class JournalEntryController : MyController
{
    private readonly IMapper _mapper;
    private readonly IJournalEntryRepository  _repository;

    public JournalEntryController(IJournalEntryRepository repository, IMapper mapper)
    {
        _mapper     = mapper;
        _repository = repository;
    }

    // ═══════════════════════════════════════════════════════════════
    // GET ALL
    // ═══════════════════════════════════════════════════════════════
    [AllowAnonymous]
    [HttpGet]
    public IActionResult Gets()
    {
        var query   = _repository.GetAll().Include(j => j.Lines);
        var results = _mapper.ProjectTo<JournalEntryListResponse>(query).ToList();
        return Ok(results);
    }

    // ═══════════════════════════════════════════════════════════════
    // GET BY ID
    // ═══════════════════════════════════════════════════════════════
    [AllowAnonymous]
    [HttpGet("{id:int}")]
    public IActionResult Get(int id)
    {
        var entry = _repository.GetAll()
            .Include(j => j.Lines)
            .FirstOrDefault(e => e.Id == id);

        if (entry == null)
            return NotFound($"Journal Entry {id} not found");

        return Ok(_mapper.Map<JournalEntryListResponse>(entry));
    }

    // ═══════════════════════════════════════════════════════════════
    // CREATE
    // ═══════════════════════════════════════════════════════════════
    [HttpPost]
    public IActionResult Create([FromBody] JournalEntryListRequest request)
    {
        if (!ModelState.IsValid) return BadRequest(ModelState);

        // Validate lines exist
        if (request.Lines == null || !request.Lines.Any())
            return BadRequest("Journal Entry must have at least one line");

        // Validate each line has an AccountCode
        var missingAcct = request.Lines
            .Where(l => string.IsNullOrWhiteSpace(l.AccountCode))
            .ToList();
        if (missingAcct.Any())
            return BadRequest($"Line(s) {string.Join(", ", missingAcct.Select(l => l.LineNum))} are missing Account Code");

        // Validate Debit = Credit
        var totalDebit  = request.Lines.Sum(l => l.Debit);
        var totalCredit = request.Lines.Sum(l => l.Credit);

        if (Math.Abs(totalDebit - totalCredit) > 0.01m)
            return BadRequest($"Debit ({totalDebit:N2}) must equal Credit ({totalCredit:N2})");

        if (totalDebit == 0)
            return BadRequest("Total amount cannot be zero");

        // Map header
        var entity = _mapper.Map<JournalEntry>(request);
        entity.JrnlNo         = GenerateJournalNumber();
        entity.TotalDebit     = totalDebit;
        entity.TotalCredit    = totalCredit;
        entity.TotalLC        = totalDebit;
        entity.TotalFC        = totalDebit * request.ExchangeRate;
        entity.Status         = "O";
        entity.IsAutoGenerated = false;
        entity.VersionNum     = 1;
        entity.CreatedAt      = DateTime.UtcNow;
        entity.InActive       = false;

        // Map lines with safety net
        int lineNum = 1;
        foreach (var lr in request.Lines)
        {
            var line = _mapper.Map<JournalEntryLine>(lr);
            line.LineNum = lineNum++;

            // ✅ SAFETY NET — ensures non-null values even if mapper has issues
            line.AccountCode = lr.AccountCode.Trim();
            line.AccountName = string.IsNullOrWhiteSpace(lr.AccountName)
                               ? lr.AccountCode.Trim()   // fallback to code
                               : lr.AccountName.Trim();
            line.CardCode    = lr.CardCode ?? string.Empty;
            line.CardName    = lr.CardName ?? string.Empty;

            // Local currency = same as base currency amount
            line.DebitLC     = line.Debit;
            line.CreditLC    = line.Credit;
            line.CreatedAt   = DateTime.UtcNow;
            line.InActive    = false;

            entity.Lines.Add(line);
        }

        _repository.Add(entity);
        _repository.Commit();

        return Ok(new
        {
            message = "Journal Entry saved successfully",
            id      = entity.Id,
            jrnlNo  = entity.JrnlNo
        });
    }

    // ═══════════════════════════════════════════════════════════════
    // UPDATE
    // ═══════════════════════════════════════════════════════════════
    [HttpPut("{id:int}")]
    public IActionResult Update(int id, [FromBody] JournalEntryUpdateRequest request)
    {
        var entry = _repository.GetAll()
            .Include(j => j.Lines)
            .FirstOrDefault(e => e.Id == id);

        if (entry == null)
            return NotFound($"Journal Entry {id} not found");

        if (entry.Status == "C")
            return BadRequest("Cannot edit a Closed (Posted) Journal Entry");
        if (entry.Status == "V")
            return BadRequest("Cannot edit a Void Journal Entry");
        if (entry.IsAutoGenerated)
            return BadRequest("Cannot edit an auto-generated Journal Entry");

        // Validate balance
        var totalDebit  = request.Lines.Sum(l => l.Debit);
        var totalCredit = request.Lines.Sum(l => l.Credit);

        if (Math.Abs(totalDebit - totalCredit) > 0.01m)
            return BadRequest($"Debit ({totalDebit:N2}) must equal Credit ({totalCredit:N2})");

        // Update header
        entry.TransDate    = request.TransDate;
        entry.DueDate      = request.DueDate;
        entry.DocDate      = request.DocDate;
        entry.RefNo        = request.RefNo;
        entry.Ref2         = request.Ref2;
        entry.Ref3         = request.Ref3;
        entry.Currency     = request.Currency ?? entry.Currency;
        entry.ExchangeRate = request.ExchangeRate;
        entry.Memo         = request.Memo;
        entry.ProjectCode  = request.ProjectCode;
        entry.CostCenter   = request.CostCenter;
        entry.TotalDebit   = totalDebit;
        entry.TotalCredit  = totalCredit;
        entry.TotalLC      = totalDebit;
        entry.TotalFC      = totalDebit * request.ExchangeRate;
        entry.UpdatedAt    = DateTime.UtcNow;
        entry.VersionNum  += 1;

        // Replace all lines
        entry.Lines.Clear();
        int lineNum = 1;
        foreach (var lr in request.Lines)
        {
            var line = _mapper.Map<JournalEntryLine>(lr);
            line.LineNum = lineNum++;

            // ✅ SAFETY NET
            line.AccountCode = lr.AccountCode.Trim();
            line.AccountName = string.IsNullOrWhiteSpace(lr.AccountName)
                               ? lr.AccountCode.Trim()
                               : lr.AccountName.Trim();
            line.CardCode    = lr.CardCode ?? string.Empty;
            line.CardName    = lr.CardName ?? string.Empty;
            line.DebitLC     = line.Debit;
            line.CreditLC    = line.Credit;
            line.CreatedAt   = DateTime.UtcNow;
            line.InActive    = false;

            entry.Lines.Add(line);
        }

        _repository.Update(entry);
        _repository.Commit();

        return NoContent();
    }

    // ═══════════════════════════════════════════════════════════════
    // POST (Close/Approve)
    // ═══════════════════════════════════════════════════════════════
    [HttpPost("{id:int}/Post")]
    public IActionResult Post(int id)
    {
        var entry = _repository.GetSingle(e => e.Id == id);
        if (entry == null)
            return NotFound($"Journal Entry {id} not found");

        if (entry.Status != "O")
            return BadRequest($"Journal Entry is not Open (current status: {entry.Status})");

        entry.Status    = "C";
        entry.UpdatedAt = DateTime.UtcNow;

        _repository.Update(entry);
        _repository.Commit();

        return Ok(new { message = "Journal Entry posted (closed) successfully", jrnlNo = entry.JrnlNo });
    }

    // ═══════════════════════════════════════════════════════════════
    // VOID
    // ═══════════════════════════════════════════════════════════════
    [HttpPost("{id:int}/Void")]
    public IActionResult Void(int id)
    {
        var entry = _repository.GetSingle(e => e.Id == id);
        if (entry == null)
            return NotFound($"Journal Entry {id} not found");

        if (entry.Status == "V")
            return BadRequest("Journal Entry is already voided");

        entry.Status    = "V";
        entry.UpdatedAt = DateTime.UtcNow;

        _repository.Update(entry);
        _repository.Commit();

        return Ok(new { message = "Journal Entry voided successfully", jrnlNo = entry.JrnlNo });
    }

    // ═══════════════════════════════════════════════════════════════
    // REVERSE — post an opposite entry that cancels the original.
    // Keeps both records (audit trail); links the reversal back via
    // BaseDocType="JE-REV" / BaseDocEntry. Debit ↔ Credit are swapped.
    // ═══════════════════════════════════════════════════════════════
    [HttpPost("{id:int}/Reverse")]
    public IActionResult Reverse(int id, [FromBody] ReverseJournalEntryRequest? request = null)
    {
        var original = _repository.GetAll()
            .Include(j => j.Lines)
            .FirstOrDefault(e => e.Id == id);

        if (original == null)
            return NotFound($"Journal Entry {id} not found");

        if (original.TransType == "RV")
            return BadRequest("This entry is itself a reversal and cannot be reversed.");
        if (original.Status == "V")
            return BadRequest("A voided entry cannot be reversed.");

        var already = _repository.GetAll()
            .FirstOrDefault(e => e.BaseDocType == "JE-REV" && e.BaseDocEntry == id);
        if (already != null)
            return BadRequest($"'{original.JrnlNo}' was already reversed by '{already.JrnlNo}'.");

        var when   = (request?.ReversalDate ?? DateTime.UtcNow).Date;
        var reason = string.IsNullOrWhiteSpace(request?.Reason) ? "" : $" — {request!.Reason!.Trim()}";

        var rev = new JournalEntry
        {
            JrnlNo          = GenerateJournalNumber(),
            TransDate       = when,
            DueDate         = when,
            DocDate         = when,
            RefNo           = original.JrnlNo,
            TransType       = "RV",
            BaseDocType     = "JE-REV",
            BaseDocEntry    = original.Id,
            Currency        = original.Currency,
            ExchangeRate    = original.ExchangeRate,
            Memo            = $"Reversal of {original.JrnlNo}{reason}",
            Status          = "O",
            IsAutoGenerated = true,
            TotalDebit      = original.TotalCredit,   // ← swapped
            TotalCredit     = original.TotalDebit,
            TotalLC         = original.TotalCredit,
            TotalFC         = original.TotalCredit * original.ExchangeRate,
            VersionNum      = 1,
            CreatedAt       = DateTime.UtcNow,
            InActive        = false,
        };

        int lineNum = 1;
        foreach (var l in original.Lines.OrderBy(x => x.LineNum))
        {
            rev.Lines.Add(new JournalEntryLine
            {
                LineNum     = lineNum++,
                AccountCode = l.AccountCode,
                AccountName = l.AccountName,
                CardCode    = l.CardCode,
                CardName    = l.CardName,
                Debit       = l.Credit,    // ← swap
                Credit      = l.Debit,
                DebitFC     = l.CreditFC,
                CreditFC    = l.DebitFC,
                DebitLC     = l.CreditLC,
                CreditLC    = l.DebitLC,
                LineMemo    = l.LineMemo,
                CostCenter  = l.CostCenter,
                Project     = l.Project,
                TaxCode     = l.TaxCode,
                TaxAmount   = -l.TaxAmount,
                Reference   = original.JrnlNo,
                CreatedAt   = DateTime.UtcNow,
                InActive    = false,
            });
        }

        _repository.Add(rev);
        _repository.Commit();

        return Ok(new
        {
            message        = $"Reversed {original.JrnlNo} → {rev.JrnlNo}",
            id             = rev.Id,
            jrnlNo         = rev.JrnlNo,
            reversedJrnlNo = original.JrnlNo,
        });
    }

    // ═══════════════════════════════════════════════════════════════
    // DELETE
    // ═══════════════════════════════════════════════════════════════
    [HttpDelete("{id:int}")]
    public IActionResult Delete(int id)
    {
        var entry = _repository.GetSingle(e => e.Id == id);
        if (entry == null)
            return NotFound($"Journal Entry {id} not found");

        if (entry.Status == "C")
            return BadRequest("Cannot delete a Posted Journal Entry. Use Void instead.");
        if (entry.IsAutoGenerated)
            return BadRequest("Cannot delete an auto-generated Journal Entry. Use Void instead.");

        entry.DeletedAt = DateTime.UtcNow;
        _repository.Remove(entry);
        _repository.Commit();

        return NoContent();
    }

    // ═══════════════════════════════════════════════════════════════
    // GET BY DATE RANGE
    // ═══════════════════════════════════════════════════════════════
    [AllowAnonymous]
    [HttpGet("DateRange")]
    public IActionResult GetByDateRange(
        [FromQuery] DateTime fromDate,
        [FromQuery] DateTime toDate)
    {
        var entries = _repository.GetAll()
            .Include(j => j.Lines)
            .Where(j => j.TransDate >= fromDate && j.TransDate <= toDate)
            .OrderByDescending(j => j.TransDate)
            .ToList();

        return Ok(_mapper.Map<List<JournalEntryListResponse>>(entries));
    }

    // ═══════════════════════════════════════════════════════════════
    // GET BY ACCOUNT CODE
    // ═══════════════════════════════════════════════════════════════
    [AllowAnonymous]
    [HttpGet("ByAccount/{accountCode}")]
    public IActionResult GetByAccount(string accountCode)
    {
        var entries = _repository.GetAll()
            .Include(j => j.Lines)
            .Where(j => j.Lines.Any(l => l.AccountCode == accountCode))
            .OrderByDescending(j => j.TransDate)
            .ToList();

        return Ok(_mapper.Map<List<JournalEntryListResponse>>(entries));
    }

    // ═══════════════════════════════════════════════════════════════
    // AUTO-CREATE (called by other modules — payments, invoices)
    // ═══════════════════════════════════════════════════════════════
    [HttpPost("Auto")]
    public IActionResult AutoCreate([FromBody] AutoJournalEntryRequest request)
    {
        if (request.Lines == null || !request.Lines.Any())
            return BadRequest("Auto Journal Entry must have at least one line");

        var totalDebit  = request.Lines.Sum(l => l.Debit);
        var totalCredit = request.Lines.Sum(l => l.Credit);

        if (Math.Abs(totalDebit - totalCredit) > 0.01m)
            return BadRequest($"Auto entry does not balance: Dr {totalDebit:N2} ≠ Cr {totalCredit:N2}");

        var entity = new JournalEntry
        {
            JrnlNo         = GenerateJournalNumber(),
            TransDate      = request.TransDate,
            DueDate        = request.TransDate,
            DocDate        = request.TransDate,
            RefNo          = request.RefNo,
            Memo           = request.Memo,
            TransType      = request.TransType ?? "JE",
            BaseDocEntry   = request.BaseDocEntry,
            BaseDocType    = request.BaseDocType,
            Currency       = "USD",
            ExchangeRate   = 1,
            TotalDebit     = totalDebit,
            TotalCredit    = totalCredit,
            TotalLC        = totalDebit,
            TotalFC        = totalDebit,
            Status         = "O",
            IsAutoGenerated = true,
            VersionNum     = 1,
            CreatedAt      = DateTime.UtcNow,
            InActive       = false,
        };

        int lineNum = 1;
        foreach (var lr in request.Lines)
        {
            var line = _mapper.Map<JournalEntryLine>(lr);
            line.LineNum     = lineNum++;
            line.AccountCode = lr.AccountCode.Trim();
            line.AccountName = string.IsNullOrWhiteSpace(lr.AccountName)
                               ? lr.AccountCode.Trim()
                               : lr.AccountName.Trim();
            line.CardCode    = lr.CardCode    ?? string.Empty;
            line.CardName    = lr.CardName    ?? string.Empty;
            line.DebitLC     = line.Debit;
            line.CreditLC    = line.Credit;
            line.CreatedAt   = DateTime.UtcNow;
            line.InActive    = false;
            entity.Lines.Add(line);
        }

        _repository.Add(entity);
        _repository.Commit();

        return Ok(new
        {
            message = "Auto Journal Entry created",
            id      = entity.Id,
            jrnlNo  = entity.JrnlNo
        });
    }

    // ═══════════════════════════════════════════════════════════════
    // HELPER — Generate Journal Number: JE-2026-00001
    // ═══════════════════════════════════════════════════════════════
    private string GenerateJournalNumber()
    {
        var year    = DateTime.Now.Year;
        var prefix  = $"JE-{year}-";
        var last    = _repository.GetAll()
            .Where(j => j.JrnlNo.StartsWith(prefix))
            .OrderByDescending(j => j.Id)
            .FirstOrDefault();

        if (last == null)
            return $"{prefix}00001";

        var parts = last.JrnlNo.Split('-');
        if (parts.Length >= 3 && int.TryParse(parts[2], out int lastNumber))
            return $"{prefix}{(lastNumber + 1):D5}";

        return $"{prefix}00001";
    }
}