using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FarmingApi.Core;

namespace FarmingApi.Modules.Financials.JournalEntry;

public class JournalEntryController : MyController
{
    private readonly IMapper _mapper;
    private readonly IJournalEntryRepository _repository;

    public JournalEntryController(IJournalEntryRepository repository, IMapper mapper)
    {
        _mapper = mapper;
        _repository = repository;
    }

    // ═══════════════════════════════════════════════════════════════
    // GET ALL
    // ═══════════════════════════════════════════════════════════════
    [AllowAnonymous]
    [HttpGet]
    public IActionResult Gets()
    {
        var iQueryable = _repository.GetAll().Include(j => j.Lines);
        var results = _mapper.ProjectTo<JournalEntryListResponse>(iQueryable).ToList();
        return Ok(results);
    }

    // ═══════════════════════════════════════════════════════════════
    // GET BY ID
    // ═══════════════════════════════════════════════════════════════
    [HttpGet("{id:int}")]
    public IActionResult Get(int id)
    {
        var journalEntry = _repository.GetAll()
            .Include(j => j.Lines)
            .FirstOrDefault(e => e.Id == id);

        if (journalEntry == null)
        {
            return BadRequest($"Journal Entry not found {id}");
        }

        var result = _mapper.Map<JournalEntryListResponse>(journalEntry);
        return Ok(result);
    }

    // ═══════════════════════════════════════════════════════════════
    // CREATE
    // ═══════════════════════════════════════════════════════════════
    [HttpPost]
    public IActionResult Create([FromBody] JournalEntryListRequest request)
    {
        if (!ModelState.IsValid) return BadRequest(ModelState);

        // Validate lines
        if (request.Lines == null || !request.Lines.Any())
            return BadRequest("Journal Entry must have at least one line");

        // Validate Debit = Credit
        var totalDebit = request.Lines.Sum(l => l.Debit);
        var totalCredit = request.Lines.Sum(l => l.Credit);

        if (totalDebit != totalCredit)
            return BadRequest($"Debit ({totalDebit:N2}) must equal Credit ({totalCredit:N2})");

        if (totalDebit == 0)
            return BadRequest("Total amount cannot be zero");

        // Create entity
        var entity = _mapper.Map<JournalEntry>(request);
        entity.JrnlNo = GenerateJournalNumber();
        entity.TotalDebit = totalDebit;
        entity.TotalCredit = totalCredit;
        entity.TotalLC = totalDebit;
        entity.TotalFC = totalDebit * request.ExchangeRate;
        entity.Status = "O";
        entity.IsAutoGenerated = false;
        entity.VersionNum = 1;
        entity.CreatedAt = DateTime.UtcNow;
        entity.InActive = false;

        // Add lines
        int lineNum = 1;
        foreach (var lineRequest in request.Lines)
        {
            var line = _mapper.Map<JournalEntryLine>(lineRequest);
            line.LineNum = lineNum++;
            line.DebitLC = line.Debit;
            line.CreditLC = line.Credit;
            line.CreatedAt = DateTime.UtcNow;
            line.InActive = false;
            entity.Lines.Add(line);
        }

        _repository.Add(entity);
        _repository.Commit();

        return Ok(new
        {
            message = "Journal Entry saved successfully",
            id = entity.Id,
            jrnlNo = entity.JrnlNo
        });
    }

    // ═══════════════════════════════════════════════════════════════
    // UPDATE
    // ═══════════════════════════════════════════════════════════════
    [HttpPut("{id}")]
    public IActionResult Update(int id, [FromBody] JournalEntryUpdateRequest request)
    {
        var journalEntry = _repository.GetAll()
            .Include(j => j.Lines)
            .FirstOrDefault(e => e.Id == id);

        if (journalEntry == null)
            return NotFound($"Journal Entry not found: {id}");

        // Cannot edit closed or void entries
        if (journalEntry.Status == "C")
            return BadRequest("Cannot edit closed Journal Entry");
        if (journalEntry.Status == "V")
            return BadRequest("Cannot edit voided Journal Entry");

        // Cannot edit auto-generated entries
        if (journalEntry.IsAutoGenerated)
            return BadRequest("Cannot edit auto-generated Journal Entry");

        // Validate Debit = Credit
        var totalDebit = request.Lines.Sum(l => l.Debit);
        var totalCredit = request.Lines.Sum(l => l.Credit);

        if (totalDebit != totalCredit)
            return BadRequest($"Debit ({totalDebit:N2}) must equal Credit ({totalCredit:N2})");

        // Update header
        journalEntry.TransDate = request.TransDate;
        journalEntry.DueDate = request.DueDate;
        journalEntry.DocDate = request.DocDate;
        journalEntry.RefNo = request.RefNo;
        journalEntry.Ref2 = request.Ref2;
        journalEntry.Ref3 = request.Ref3;
        journalEntry.Currency = request.Currency;
        journalEntry.ExchangeRate = request.ExchangeRate;
        journalEntry.Memo = request.Memo;
        journalEntry.ProjectCode = request.ProjectCode;
        journalEntry.CostCenter = request.CostCenter;
        journalEntry.TotalDebit = totalDebit;
        journalEntry.TotalCredit = totalCredit;
        journalEntry.TotalLC = totalDebit;
        journalEntry.TotalFC = totalDebit * request.ExchangeRate;
        journalEntry.UpdatedAt = DateTime.UtcNow;
        journalEntry.VersionNum += 1;

        // Replace lines
        journalEntry.Lines.Clear();
        int lineNum = 1;
        foreach (var lineRequest in request.Lines)
        {
            var line = _mapper.Map<JournalEntryLine>(lineRequest);
            line.LineNum = lineNum++;
            line.DebitLC = line.Debit;
            line.CreditLC = line.Credit;
            line.CreatedAt = DateTime.UtcNow;
            line.InActive = false;
            journalEntry.Lines.Add(line);
        }

        _repository.Update(journalEntry);
        _repository.Commit();

        return NoContent();
    }

    // ═══════════════════════════════════════════════════════════════
    // POST (Close/Approve)
    // ═══════════════════════════════════════════════════════════════
    [HttpPost("{id}/Post")]
    public IActionResult Post(int id)
    {
        var journalEntry = _repository.GetSingle(e => e.Id == id);
        if (journalEntry == null)
            return NotFound($"Journal Entry not found: {id}");

        if (journalEntry.Status != "O")
            return BadRequest($"Journal Entry is not Open (current status: {journalEntry.Status})");

        journalEntry.Status = "C"; // Closed/Posted
        journalEntry.UpdatedAt = DateTime.UtcNow;

        _repository.Update(journalEntry);
        _repository.Commit();

        return Ok(new { message = "Journal Entry posted successfully" });
    }

    // ═══════════════════════════════════════════════════════════════
    // VOID
    // ═══════════════════════════════════════════════════════════════
    [HttpPost("{id}/Void")]
    public IActionResult Void(int id)
    {
        var journalEntry = _repository.GetSingle(e => e.Id == id);
        if (journalEntry == null)
            return NotFound($"Journal Entry not found: {id}");

        if (journalEntry.Status == "V")
            return BadRequest("Journal Entry is already voided");

        journalEntry.Status = "V"; // Void
        journalEntry.UpdatedAt = DateTime.UtcNow;

        _repository.Update(journalEntry);
        _repository.Commit();

        return Ok(new { message = "Journal Entry voided successfully" });
    }

    // ═══════════════════════════════════════════════════════════════
    // DELETE
    // ═══════════════════════════════════════════════════════════════
    [HttpDelete("{id}")]
    public IActionResult Delete(int id)
    {
        var journalEntry = _repository.GetSingle(e => e.Id == id);
        if (journalEntry == null)
            return BadRequest($"Journal Entry not found {id}");

        // Cannot delete posted or auto-generated
        if (journalEntry.Status == "C")
            return BadRequest("Cannot delete posted Journal Entry. Use Void instead.");

        if (journalEntry.IsAutoGenerated)
            return BadRequest("Cannot delete auto-generated Journal Entry. Use Void instead.");

        journalEntry.DeletedAt = DateTime.UtcNow;
        _repository.Remove(journalEntry);
        _repository.Commit();

        return NoContent();
    }

    // ═══════════════════════════════════════════════════════════════
    // GET BY DATE RANGE
    // ═══════════════════════════════════════════════════════════════
    [HttpGet("DateRange")]
    public IActionResult GetByDateRange([FromQuery] DateTime fromDate, [FromQuery] DateTime toDate)
    {
        var entries = _repository.GetAll()
            .Include(j => j.Lines)
            .Where(j => j.TransDate >= fromDate && j.TransDate <= toDate)
            .OrderByDescending(j => j.TransDate)
            .ToList();

        var results = _mapper.Map<List<JournalEntryListResponse>>(entries);
        return Ok(results);
    }

    // ═══════════════════════════════════════════════════════════════
    // GET BY ACCOUNT
    // ═══════════════════════════════════════════════════════════════
    [HttpGet("ByAccount/{accountCode}")]
    public IActionResult GetByAccount(string accountCode)
    {
        var entries = _repository.GetAll()
            .Include(j => j.Lines)
            .Where(j => j.Lines.Any(l => l.AccountCode == accountCode))
            .OrderByDescending(j => j.TransDate)
            .ToList();

        var results = _mapper.Map<List<JournalEntryListResponse>>(entries);
        return Ok(results);
    }

    // ═══════════════════════════════════════════════════════════════
    // HELPER: Generate Journal Number
    // ═══════════════════════════════════════════════════════════════
    private string GenerateJournalNumber()
    {
        var year = DateTime.Now.Year;
        var lastJournal = _repository.GetAll()
            .Where(j => j.JrnlNo.StartsWith($"JE-{year}"))
            .OrderByDescending(j => j.Id)
            .FirstOrDefault();

        if (lastJournal == null)
            return $"JE-{year}-00001";

        var parts = lastJournal.JrnlNo.Split('-');
        if (parts.Length >= 3 && int.TryParse(parts[2], out int lastNumber))
        {
            return $"JE-{year}-{(lastNumber + 1).ToString("D5")}";
        }

        return $"JE-{year}-00001";
    }
}