using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using FarmingApi.Core;

namespace FarmingApi.Modules.Financials.JournalEntry;

// ═══════════════════════════════════════════════════════════════════
// JOURNAL ENTRY HEADER (KJRN)
// ═══════════════════════════════════════════════════════════════════
public class JournalEntry : AuditableEntity
{
    public string  JrnlNo       { get; set; } = null!;   // Auto: JE-2026-00001
    public DateTime TransDate   { get; set; }             // Transaction Date
    public DateTime DueDate     { get; set; }             // Due Date
    public DateTime DocDate     { get; set; }             // Document Date
    public string? RefNo        { get; set; }             // Reference Number
    public string? Ref2         { get; set; }             // Reference 2
    public string? Ref3         { get; set; }             // Reference 3
    public string  TransType    { get; set; } = "JE";    // JE = Journal Entry
    public int?    BaseDocEntry { get; set; }             // Source document ID
    public string? BaseDocType  { get; set; }             // Source document type
    public decimal TotalDebit   { get; set; }
    public decimal TotalCredit  { get; set; }
    public decimal TotalLC      { get; set; }             // Local Currency Total
    public decimal TotalFC      { get; set; }             // Foreign Currency Total
    public string  Currency     { get; set; } = "USD";
    public decimal ExchangeRate { get; set; } = 1;
    public string? Memo         { get; set; }             // Description / Remarks
    public string  Status       { get; set; } = "O";     // O=Open, C=Closed, V=Void
    public bool    IsAutoGenerated { get; set; } = false;
    public string? ProjectCode  { get; set; }
    public string? CostCenter   { get; set; }
    public int?    UserSign     { get; set; }
    public int?    UserSign2    { get; set; }
    public int     VersionNum   { get; set; } = 1;

    // Navigation
    public ICollection<JournalEntryLine> Lines { get; set; } = new List<JournalEntryLine>();
}

// ═══════════════════════════════════════════════════════════════════
// JOURNAL ENTRY LINE (JRN1)
// ═══════════════════════════════════════════════════════════════════
public class JournalEntryLine : AuditableEntity
{
    public int     JournalEntryId { get; set; }
    public int     LineNum        { get; set; }

    // ✅ AccountCode required, AccountName with fallback
    public string  AccountCode    { get; set; } = null!;
    public string  AccountName    { get; set; } = string.Empty; // non-null, set in controller

    // ✅ CardCode/CardName nullable — not all lines have a Business Partner
    public string? CardCode       { get; set; }
    public string? CardName       { get; set; }

    // Amounts
    public decimal Debit          { get; set; }
    public decimal Credit         { get; set; }
    public decimal DebitFC        { get; set; }   // Foreign Currency Debit
    public decimal CreditFC       { get; set; }   // Foreign Currency Credit
    public decimal DebitLC        { get; set; }   // Local Currency Debit
    public decimal CreditLC       { get; set; }   // Local Currency Credit

    // Details
    public string?   LineMemo     { get; set; }
    public string?   CostCenter   { get; set; }
    public string?   Project      { get; set; }
    public string?   TaxCode      { get; set; }
    public decimal   TaxAmount    { get; set; }
    public string?   Reference    { get; set; }
    public DateTime? DueDate      { get; set; }

    // Navigation
    public JournalEntry JournalEntry { get; set; } = null!;
}

// ═══════════════════════════════════════════════════════════════════
// EF CONFIGURATIONS
// ═══════════════════════════════════════════════════════════════════
public class JournalEntryConfig : IEntityTypeConfiguration<JournalEntry>
{
    public void Configure(EntityTypeBuilder<JournalEntry> builder)
    {
        builder.ToTable("KJRN");
        builder.HasKey(x => x.Id);

        builder.Property(m => m.JrnlNo).HasMaxLength(50).IsRequired();
        builder.Property(m => m.TransType).HasMaxLength(10).HasDefaultValue("JE");
        builder.Property(m => m.BaseDocType).HasMaxLength(10);
        builder.Property(m => m.RefNo).HasMaxLength(50);
        builder.Property(m => m.Ref2).HasMaxLength(50);
        builder.Property(m => m.Ref3).HasMaxLength(50);
        builder.Property(m => m.Currency).HasMaxLength(3).HasDefaultValue("USD");
        builder.Property(m => m.Memo).HasMaxLength(500);
        builder.Property(m => m.Status).HasMaxLength(1).HasDefaultValue("O");
        builder.Property(m => m.ProjectCode).HasMaxLength(50);
        builder.Property(m => m.CostCenter).HasMaxLength(50);
        builder.Property(m => m.VersionNum).HasDefaultValue(1);

        builder.Property(m => m.TotalDebit).HasPrecision(18, 2);
        builder.Property(m => m.TotalCredit).HasPrecision(18, 2);
        builder.Property(m => m.TotalLC).HasPrecision(18, 2);
        builder.Property(m => m.TotalFC).HasPrecision(18, 2);
        builder.Property(m => m.ExchangeRate).HasPrecision(18, 6);

        builder.HasIndex(m => m.JrnlNo).IsUnique();
        builder.HasIndex(m => m.TransType);
        builder.HasIndex(m => m.TransDate);
        builder.HasIndex(m => new { m.BaseDocType, m.BaseDocEntry });
    }
}

public class JournalEntryLineConfig : IEntityTypeConfiguration<JournalEntryLine>
{
    public void Configure(EntityTypeBuilder<JournalEntryLine> builder)
    {
        builder.ToTable("JRN1");
        builder.HasKey(x => x.Id);

        builder.Property(m => m.AccountCode).HasMaxLength(50).IsRequired();
        builder.Property(m => m.AccountName).HasMaxLength(200).IsRequired().HasDefaultValue(string.Empty);

        // ✅ CardCode/CardName — nullable (not all lines need a Business Partner)
        builder.Property(m => m.CardCode).HasMaxLength(50).IsRequired(false);
        builder.Property(m => m.CardName).HasMaxLength(200).IsRequired(false);

        builder.Property(m => m.LineMemo).HasMaxLength(500);
        builder.Property(m => m.CostCenter).HasMaxLength(50);
        builder.Property(m => m.Project).HasMaxLength(50);
        builder.Property(m => m.TaxCode).HasMaxLength(20);
        builder.Property(m => m.Reference).HasMaxLength(50);

        builder.Property(m => m.Debit).HasPrecision(18, 2);
        builder.Property(m => m.Credit).HasPrecision(18, 2);
        builder.Property(m => m.DebitFC).HasPrecision(18, 2);
        builder.Property(m => m.CreditFC).HasPrecision(18, 2);
        builder.Property(m => m.DebitLC).HasPrecision(18, 2);
        builder.Property(m => m.CreditLC).HasPrecision(18, 2);
        builder.Property(m => m.TaxAmount).HasPrecision(18, 2);

        builder.HasOne(m => m.JournalEntry)
            .WithMany(j => j.Lines)
            .HasForeignKey(m => m.JournalEntryId)
            .OnDelete(DeleteBehavior.Cascade);

        builder.HasIndex(m => m.JournalEntryId);
        builder.HasIndex(m => m.AccountCode);
        builder.HasIndex(m => m.CardCode);
    }
}