using AutoMapper;

namespace FarmingApi.Modules.Financials.JournalEntry;

public class JournalEntryMapper : Profile
{
    public JournalEntryMapper()
    {
        // ═══════════════════════════════════════════════════════════════
        // ENTITY -> RESPONSE
        // ═══════════════════════════════════════════════════════════════
        CreateMap<JournalEntry, JournalEntryListResponse>()
            .ForMember(d => d.Lines, opt => opt.MapFrom(s => s.Lines));

        CreateMap<JournalEntryLine, JournalEntryLineResponse>();

        // ═══════════════════════════════════════════════════════════════
        // CREATE REQUEST -> ENTITY
        // ═══════════════════════════════════════════════════════════════
        CreateMap<JournalEntryListRequest, JournalEntry>()
            .ForMember(d => d.Id, opt => opt.Ignore())
            .ForMember(d => d.JrnlNo, opt => opt.Ignore())
            .ForMember(d => d.BaseDocEntry, opt => opt.Ignore())
            .ForMember(d => d.BaseDocType, opt => opt.Ignore())
            .ForMember(d => d.TotalDebit, opt => opt.Ignore())
            .ForMember(d => d.TotalCredit, opt => opt.Ignore())
            .ForMember(d => d.TotalLC, opt => opt.Ignore())
            .ForMember(d => d.TotalFC, opt => opt.Ignore())
            .ForMember(d => d.Status, opt => opt.Ignore())
            .ForMember(d => d.IsAutoGenerated, opt => opt.Ignore())
            .ForMember(d => d.UserSign, opt => opt.Ignore())
            .ForMember(d => d.UserSign2, opt => opt.Ignore())
            .ForMember(d => d.VersionNum, opt => opt.Ignore())
            .ForMember(d => d.Lines, opt => opt.Ignore())
            .ForMember(d => d.CreatedAt, opt => opt.Ignore())
            .ForMember(d => d.UpdatedAt, opt => opt.Ignore())
            .ForMember(d => d.DeletedAt, opt => opt.Ignore())
            .ForMember(d => d.InActive, opt => opt.Ignore());

        CreateMap<JournalEntryLineRequest, JournalEntryLine>()
            .ForMember(d => d.Id, opt => opt.Ignore())
            .ForMember(d => d.JournalEntryId, opt => opt.Ignore())
            .ForMember(d => d.AccountName, opt => opt.Ignore())
            .ForMember(d => d.CardName, opt => opt.Ignore())
            .ForMember(d => d.DebitLC, opt => opt.Ignore())
            .ForMember(d => d.CreditLC, opt => opt.Ignore())
            .ForMember(d => d.JournalEntry, opt => opt.Ignore())
            .ForMember(d => d.CreatedAt, opt => opt.Ignore())
            .ForMember(d => d.UpdatedAt, opt => opt.Ignore())
            .ForMember(d => d.DeletedAt, opt => opt.Ignore())
            .ForMember(d => d.InActive, opt => opt.Ignore());
    }
}