using AutoMapper;

namespace FarmingApi.Modules.Financials.JournalEntry;

public class JournalEntryMapper : Profile
{
    public JournalEntryMapper()
    {
        // ═══════════════════════════════════════════════════════════
        // ENTITY → RESPONSE
        // ═══════════════════════════════════════════════════════════
        CreateMap<JournalEntry, JournalEntryListResponse>()
            .ForMember(d => d.Lines, opt => opt.MapFrom(s => s.Lines));

        CreateMap<JournalEntryLine, JournalEntryLineResponse>();

        // ═══════════════════════════════════════════════════════════
        // CREATE REQUEST → ENTITY
        // ═══════════════════════════════════════════════════════════
        CreateMap<JournalEntryListRequest, JournalEntry>()
            .ForMember(d => d.Id,             opt => opt.Ignore())
            .ForMember(d => d.JrnlNo,         opt => opt.Ignore())   // set by controller
            .ForMember(d => d.BaseDocEntry,   opt => opt.Ignore())
            .ForMember(d => d.BaseDocType,    opt => opt.Ignore())
            .ForMember(d => d.TotalDebit,     opt => opt.Ignore())   // calculated by controller
            .ForMember(d => d.TotalCredit,    opt => opt.Ignore())   // calculated by controller
            .ForMember(d => d.TotalLC,        opt => opt.Ignore())   // calculated by controller
            .ForMember(d => d.TotalFC,        opt => opt.Ignore())   // calculated by controller
            .ForMember(d => d.Status,         opt => opt.Ignore())   // set to "O" by controller
            .ForMember(d => d.IsAutoGenerated,opt => opt.Ignore())   // set to false by controller
            .ForMember(d => d.UserSign,       opt => opt.Ignore())
            .ForMember(d => d.UserSign2,      opt => opt.Ignore())
            .ForMember(d => d.VersionNum,     opt => opt.Ignore())   // set to 1 by controller
            .ForMember(d => d.Lines,          opt => opt.Ignore())   // added manually in controller
            .ForMember(d => d.CreatedAt,      opt => opt.Ignore())
            .ForMember(d => d.UpdatedAt,      opt => opt.Ignore())
            .ForMember(d => d.DeletedAt,      opt => opt.Ignore())
            .ForMember(d => d.InActive,       opt => opt.Ignore());

        // ═══════════════════════════════════════════════════════════
        // LINE REQUEST → LINE ENTITY
        // ✅ AccountName mapped with fallback to AccountCode
        // ✅ CardName mapped with fallback to empty string
        // ═══════════════════════════════════════════════════════════
        CreateMap<JournalEntryLineRequest, JournalEntryLine>()
            .ForMember(d => d.Id,             opt => opt.Ignore())
            .ForMember(d => d.JournalEntryId, opt => opt.Ignore())   // set by controller
            // ✅ FIXED: AccountName = request value, fallback to AccountCode if empty
            .ForMember(d => d.AccountName, opt => opt.MapFrom(
                s => string.IsNullOrWhiteSpace(s.AccountName)
                     ? s.AccountCode
                     : s.AccountName.Trim()))
            // ✅ FIXED: CardName = request value or empty string (was ignored → null crash)
            .ForMember(d => d.CardName, opt => opt.MapFrom(
                s => s.CardName ?? string.Empty))
            // ✅ CardCode nullable — default empty string
            .ForMember(d => d.CardCode, opt => opt.MapFrom(
                s => s.CardCode ?? string.Empty))
            .ForMember(d => d.DebitLC,        opt => opt.Ignore())   // set by controller
            .ForMember(d => d.CreditLC,       opt => opt.Ignore())   // set by controller
            .ForMember(d => d.JournalEntry,   opt => opt.Ignore())
            .ForMember(d => d.CreatedAt,      opt => opt.Ignore())
            .ForMember(d => d.UpdatedAt,      opt => opt.Ignore())
            .ForMember(d => d.DeletedAt,      opt => opt.Ignore())
            .ForMember(d => d.InActive,       opt => opt.Ignore());

        // ═══════════════════════════════════════════════════════════
        // AUTO LINE REQUEST → LINE ENTITY (for auto-generated entries)
        // ═══════════════════════════════════════════════════════════
        CreateMap<AutoJournalEntryLine, JournalEntryLine>()
            .ForMember(d => d.Id,             opt => opt.Ignore())
            .ForMember(d => d.JournalEntryId, opt => opt.Ignore())
            .ForMember(d => d.LineNum,        opt => opt.Ignore())
            .ForMember(d => d.AccountName, opt => opt.MapFrom(
                s => string.IsNullOrWhiteSpace(s.AccountName)
                     ? s.AccountCode
                     : s.AccountName.Trim()))
            .ForMember(d => d.CardName, opt => opt.MapFrom(
                s => s.CardName ?? string.Empty))
            .ForMember(d => d.CardCode, opt => opt.MapFrom(
                s => s.CardCode ?? string.Empty))
            .ForMember(d => d.DebitFC,        opt => opt.Ignore())
            .ForMember(d => d.CreditFC,       opt => opt.Ignore())
            .ForMember(d => d.DebitLC,        opt => opt.Ignore())
            .ForMember(d => d.CreditLC,       opt => opt.Ignore())
            .ForMember(d => d.TaxCode,        opt => opt.Ignore())
            .ForMember(d => d.TaxAmount,      opt => opt.Ignore())
            .ForMember(d => d.Reference,      opt => opt.Ignore())
            .ForMember(d => d.DueDate,        opt => opt.Ignore())
            .ForMember(d => d.JournalEntry,   opt => opt.Ignore())
            .ForMember(d => d.CreatedAt,      opt => opt.Ignore())
            .ForMember(d => d.UpdatedAt,      opt => opt.Ignore())
            .ForMember(d => d.DeletedAt,      opt => opt.Ignore())
            .ForMember(d => d.InActive,       opt => opt.Ignore());
    }
}