using System;
using System.Collections.Generic;

namespace FarmingApi.Modules.Financials.JournalEntry;

// ═══════════════════════════════════════════════════════════════════
// RESPONSE DTOs
// ═══════════════════════════════════════════════════════════════════
public class JournalEntryListResponse
{
    public int Id { get; set; }
    public string JrnlNo { get; set; } = null!;
    public DateTime TransDate { get; set; }
    public DateTime DueDate { get; set; }
    public DateTime DocDate { get; set; }
    public string? RefNo { get; set; }
    public string? Ref2 { get; set; }
    public string? Ref3 { get; set; }
    public string? TransType { get; set; }
    public int? BaseDocEntry { get; set; }
    public string? BaseDocType { get; set; }
    public decimal TotalDebit { get; set; }
    public decimal TotalCredit { get; set; }
    public decimal TotalLC { get; set; }
    public decimal TotalFC { get; set; }
    public string? Currency { get; set; }
    public decimal ExchangeRate { get; set; }
    public string? Memo { get; set; }
    public string? Status { get; set; }
    public bool IsAutoGenerated { get; set; }
    public string? ProjectCode { get; set; }
    public string? CostCenter { get; set; }
    public int VersionNum { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }
    public bool InActive { get; set; }
    public List<JournalEntryLineResponse> Lines { get; set; } = new();
}

public class JournalEntryLineResponse
{
    public int Id { get; set; }
    public int LineNum { get; set; }
    public string AccountCode { get; set; } = null!; 
    public string AccountName { get; set; } = null!; 
    public string CardCode { get; set; } = null!; 
    public string CardName { get; set; } = null!; 
    public decimal Debit { get; set; }
    public decimal Credit { get; set; }
    public decimal DebitFC { get; set; }
    public decimal CreditFC { get; set; }
    public string? LineMemo { get; set; }
    public string? CostCenter { get; set; }
    public string? Project { get; set; }
    public string ?TaxCode { get; set; }
    public decimal TaxAmount { get; set; }
    public string ?Reference { get; set; }
    public DateTime? DueDate { get; set; }
}

// ═══════════════════════════════════════════════════════════════════
// REQUEST DTOs
// ═══════════════════════════════════════════════════════════════════
public class JournalEntryListRequest
{
    public DateTime TransDate { get; set; }
    public DateTime DueDate { get; set; }
    public DateTime DocDate { get; set; }
    public string ?RefNo { get; set; }
    public string ?Ref2 { get; set; }
    public string ?Ref3 { get; set; }
    public string TransType { get; set; } = "JE";
    public string Currency { get; set; } = "USD";
    public decimal ExchangeRate { get; set; } = 1;
    public string? Memo { get; set; }
    public string? ProjectCode { get; set; }
    public string? CostCenter { get; set; }
    public List<JournalEntryLineRequest> Lines { get; set; } = new();
}

public class JournalEntryLineRequest
{
    public int LineNum { get; set; }
    public string AccountCode { get; set; } = null!; 
    public string CardCode { get; set; } = null!; 
    public decimal Debit { get; set; }
    public decimal Credit { get; set; }
    public decimal DebitFC { get; set; }
    public decimal CreditFC { get; set; }
    public string? LineMemo { get; set; }
    public string? CostCenter { get; set; }
    public string? Project { get; set; }
    public string? TaxCode { get; set; }
    public decimal TaxAmount { get; set; }
    public string? Reference { get; set; }
    public DateTime? DueDate { get; set; }
}

public class JournalEntryUpdateRequest
{
    public DateTime TransDate { get; set; }
    public DateTime DueDate { get; set; }
    public DateTime DocDate { get; set; }
    public string? RefNo { get; set; }
    public string? Ref2 { get; set; }
    public string? Ref3 { get; set; }
    public string? Currency { get; set; }
    public decimal ExchangeRate { get; set; }
    public string? Memo { get; set; }
    public string? ProjectCode { get; set; }
    public string? CostCenter { get; set; }
    public List<JournalEntryLineRequest> Lines { get; set; } = new();
}

// Auto-creation request (for other services)
public class AutoJournalEntryRequest
{
    public string? TransType { get; set; }
    public int BaseDocEntry { get; set; }
    public string? BaseDocType { get; set; }
    public DateTime TransDate { get; set; }
    public string? RefNo { get; set; }
    public string? Memo { get; set; }
    public List<AutoJournalEntryLine> Lines { get; set; } = new();
}

public class AutoJournalEntryLine
{
    public string AccountCode { get; set; } = null!; 
    public decimal Debit { get; set; }
    public decimal Credit { get; set; }
    public string? LineMemo { get; set; }
    public string? CostCenter { get; set; }
    public string? Project { get; set; }
}