namespace FarmingApi.Modules.Financials.JournalEntry;

// ═══════════════════════════════════════════════════════════════════
// RESPONSE DTOs
// ═══════════════════════════════════════════════════════════════════
public class JournalEntryListResponse
{
    public int       Id              { get; set; }
    public string    JrnlNo          { get; set; } = null!;
    public DateTime  TransDate       { get; set; }
    public DateTime  DueDate         { get; set; }
    public DateTime  DocDate         { get; set; }
    public string?   RefNo           { get; set; }
    public string?   Ref2            { get; set; }
    public string?   Ref3            { get; set; }
    public string?   TransType       { get; set; }
    public int?      BaseDocEntry    { get; set; }
    public string?   BaseDocType     { get; set; }
    public decimal   TotalDebit      { get; set; }
    public decimal   TotalCredit     { get; set; }
    public decimal   TotalLC         { get; set; }
    public decimal   TotalFC         { get; set; }
    public string?   Currency        { get; set; }
    public decimal   ExchangeRate    { get; set; }
    public string?   Memo            { get; set; }
    public string?   Status          { get; set; }
    public bool      IsAutoGenerated { get; set; }
    public string?   ProjectCode     { get; set; }
    public string?   CostCenter      { get; set; }
    public int       VersionNum      { get; set; }
    public DateTime  CreatedAt       { get; set; }
    public DateTime? UpdatedAt       { get; set; }
    public bool      InActive        { get; set; }
    public List<JournalEntryLineResponse> Lines { get; set; } = new();
}

public class JournalEntryLineResponse
{
    public int       Id          { get; set; }
    public int       LineNum     { get; set; }
    public string    AccountCode { get; set; } = null!;
    public string    AccountName { get; set; } = null!;
    public string?   CardCode    { get; set; }   // ✅ nullable
    public string?   CardName    { get; set; }   // ✅ nullable
    public decimal   Debit       { get; set; }
    public decimal   Credit      { get; set; }
    public decimal   DebitFC     { get; set; }
    public decimal   CreditFC    { get; set; }
    public decimal   DebitLC     { get; set; }
    public decimal   CreditLC    { get; set; }
    public string?   LineMemo    { get; set; }
    public string?   CostCenter  { get; set; }
    public string?   Project     { get; set; }
    public string?   TaxCode     { get; set; }
    public decimal   TaxAmount   { get; set; }
    public string?   Reference   { get; set; }
    public DateTime? DueDate     { get; set; }
}

// ═══════════════════════════════════════════════════════════════════
// CREATE REQUEST
// ═══════════════════════════════════════════════════════════════════
public class JournalEntryListRequest
{
    public DateTime  TransDate    { get; set; }
    public DateTime  DueDate      { get; set; }
    public DateTime  DocDate      { get; set; }
    public string?   RefNo        { get; set; }
    public string?   Ref2         { get; set; }
    public string?   Ref3         { get; set; }
    public string    TransType    { get; set; } = "JE";
    public string    Currency     { get; set; } = "USD";
    public decimal   ExchangeRate { get; set; } = 1;
    public string?   Memo         { get; set; }
    public string?   ProjectCode  { get; set; }
    public string?   CostCenter   { get; set; }
    public List<JournalEntryLineRequest> Lines { get; set; } = new();
}

// ═══════════════════════════════════════════════════════════════════
// LINE REQUEST — ✅ AccountName and CardName added
// ═══════════════════════════════════════════════════════════════════
public class JournalEntryLineRequest
{
    public int       LineNum     { get; set; }

    // ✅ Account — AccountCode required, AccountName added (was missing → caused null crash)
    public string    AccountCode { get; set; } = null!;
    public string?   AccountName { get; set; }   // ✅ FIXED — was missing, now optional

    // ✅ Business Partner — both nullable (not required for every line)
    public string?   CardCode    { get; set; }   // ✅ FIXED — was = null! (required), now optional
    public string?   CardName    { get; set; }   // ✅ FIXED — was missing, now optional

    // Amounts
    public decimal   Debit       { get; set; }
    public decimal   Credit      { get; set; }
    public decimal   DebitFC     { get; set; }
    public decimal   CreditFC    { get; set; }

    // Details
    public string?   LineMemo    { get; set; }
    public string?   CostCenter  { get; set; }
    public string?   Project     { get; set; }
    public string?   TaxCode     { get; set; }
    public decimal   TaxAmount   { get; set; }
    public string?   Reference   { get; set; }
    public DateTime? DueDate     { get; set; }
}

// ═══════════════════════════════════════════════════════════════════
// UPDATE REQUEST
// ═══════════════════════════════════════════════════════════════════
public class JournalEntryUpdateRequest
{
    public DateTime  TransDate    { get; set; }
    public DateTime  DueDate      { get; set; }
    public DateTime  DocDate      { get; set; }
    public string?   RefNo        { get; set; }
    public string?   Ref2         { get; set; }
    public string?   Ref3         { get; set; }
    public string?   Currency     { get; set; }
    public decimal   ExchangeRate { get; set; }
    public string?   Memo         { get; set; }
    public string?   ProjectCode  { get; set; }
    public string?   CostCenter   { get; set; }
    public List<JournalEntryLineRequest> Lines { get; set; } = new();
}

// ═══════════════════════════════════════════════════════════════════
// REVERSE REQUEST — posts an opposite entry that cancels the original.
// ═══════════════════════════════════════════════════════════════════
public class ReverseJournalEntryRequest
{
    /// <summary>When the reversing entry is dated. Defaults to today.</summary>
    public DateTime? ReversalDate { get; set; }
    public string?   Reason       { get; set; }
}

// ═══════════════════════════════════════════════════════════════════
// AUTO-CREATION REQUEST (for payment / invoice services)
// ═══════════════════════════════════════════════════════════════════
public class AutoJournalEntryRequest
{
    public string?   TransType    { get; set; }
    public int       BaseDocEntry { get; set; }
    public string?   BaseDocType  { get; set; }
    public DateTime  TransDate    { get; set; }
    public string?   RefNo        { get; set; }
    public string?   Memo         { get; set; }
    public List<AutoJournalEntryLine> Lines { get; set; } = new();
}

public class AutoJournalEntryLine
{
    public string   AccountCode { get; set; } = null!;
    public string?  AccountName { get; set; }
    public string?  CardCode    { get; set; }
    public string?  CardName    { get; set; }
    public decimal  Debit       { get; set; }
    public decimal  Credit      { get; set; }
    public string?  LineMemo    { get; set; }
    public string?  CostCenter  { get; set; }
    public string?  Project     { get; set; }
}