using FarmingApi.Modules.Financials.GLAccountDetermination;
using FarmingApi.Modules.Financials.JournalEntry;
using BPEntity = FarmingApi.Modules.BusinessPartners.BusinessPartnersMaster.BusinessPartnersMaster;

namespace FarmingApi.Modules.Banking.OutgoingPayment;

// ═══════════════════════════════════════════════════════════════════
// OUTGOING PAYMENT JOURNAL SERVICE
// Auto-creates a Journal Entry when an Outgoing Payment is created.
//
//   DR  Accounts Payable       AppliedAmount (= Σ applied+discount+wht on invoices)
//   DR  Vendor Deposit         UnappliedAmount   (advance not tied to an invoice, if any)
//   CR  Cash / Bank            DocTotal − discount − WHT   (real cash disbursed)
//   CR  Purchase Discount      Σ discount   (only if > 0)
//   CR  Withholding Tax Payable Σ WHT       (only if > 0)
//
// Uses MyDbContext directly so it joins the SAME transaction as the payment
// save. Caller commits.
// ═══════════════════════════════════════════════════════════════════
public interface IOutgoingPaymentJournalService
{
    JournalEntry CreateJournalEntry(OutgoingPayment payment, BPEntity? vendor);
}

public class OutgoingPaymentJournalService : IOutgoingPaymentJournalService
{
    private readonly MyDbContext _db;

    public OutgoingPaymentJournalService(MyDbContext db) => _db = db;

    public JournalEntry CreateJournalEntry(OutgoingPayment payment, BPEntity? vendor)
    {
        var gl = _db.Set<GLAccountDetermination>().FirstOrDefault()
            ?? throw new InvalidOperationException(
                "GL Account Determination (KGLD) is not configured. " +
                "Set a Cash/Bank account and an Accounts Payable account first.");

        // ── Debit account: the Payment Means GL, else Cash/Bank from KGLD ──
        var cashCode = !string.IsNullOrWhiteSpace(payment.BankAccount)
            ? payment.BankAccount
            : (payment.PaymentMethod == "Cash" ? gl.CashAccount : gl.BankAccount)
              ?? gl.CashAccount ?? gl.BankAccount;

        // ── Credit account: vendor AP override → KGLD AP control ──
        var apCode = gl.AccountsPayable;

        if (string.IsNullOrWhiteSpace(cashCode))
            throw new InvalidOperationException(
                "No Cash/Bank account resolved — set the payment's account or the " +
                "Cash/Bank account in GL Account Determination (KGLD).");
        if (string.IsNullOrWhiteSpace(apCode))
            throw new InvalidOperationException(
                "Accounts Payable account is not set in GL Account Determination (KGLD).");

        var totalDiscount = payment.Invoices.Sum(i => i.DiscountAmount);
        var totalWht      = payment.Invoices.Sum(i => i.WithholdingTax);
        var apClearing    = payment.AppliedAmount;       // Σ applied + discount + wht
        var advance       = payment.UnappliedAmount;     // portion not tied to an invoice
        var cashOut       = payment.DocTotal - totalDiscount - totalWht;

        if (payment.DocTotal <= 0)
            throw new InvalidOperationException(
                $"Cannot post payment {payment.DocNum}: amount is {payment.DocTotal}.");

        if (totalDiscount > 0 && string.IsNullOrWhiteSpace(gl.PurchaseDiscount))
            throw new InvalidOperationException(
                "This payment includes a discount but Purchase Discount account is not set in KGLD.");
        if (totalWht > 0 && string.IsNullOrWhiteSpace(gl.WithholdingTaxPayable))
            throw new InvalidOperationException(
                "This payment includes withholding tax but Withholding Tax Payable account is not set in KGLD.");
        if (advance > 0 && string.IsNullOrWhiteSpace(gl.VendorDeposit))
            throw new InvalidOperationException(
                "This payment includes an unapplied advance but Vendor Deposit account is not set in KGLD.");

        var je = new JournalEntry
        {
            JrnlNo          = GenerateJournalNumber(),
            TransDate       = payment.DocDate,
            DueDate         = payment.DueDate,
            DocDate         = payment.DocDate,
            RefNo           = payment.DocNum,
            Memo            = $"Outgoing Payment {payment.DocNum} — {payment.CardName}",
            TransType       = "KPYO",
            BaseDocType     = "KPYO",
            Currency        = payment.Currency,
            ExchangeRate    = payment.ExchangeRate,
            Status          = "O",
            IsAutoGenerated = true,
            VersionNum      = 1,
            CreatedAt       = DateTime.UtcNow,
            InActive        = false,
        };

        int lineNum = 1;

        // DR: Accounts Payable (clears the invoice debt: applied + discount + wht)
        if (apClearing > 0)
        {
            je.Lines.Add(new JournalEntryLine
            {
                LineNum     = lineNum++,
                AccountCode = apCode!,
                AccountName = "Accounts Payable",
                CardCode    = payment.CardCode,
                CardName    = payment.CardName,
                Debit       = apClearing,
                Credit      = 0,
                DebitLC     = apClearing,
                CreditLC    = 0,
                LineMemo    = $"AP cleared — {payment.DocNum}",
                CreatedAt   = DateTime.UtcNow,
                InActive    = false,
            });
        }

        // DR: Vendor Deposit (advance not yet applied to an invoice)
        if (advance > 0)
        {
            je.Lines.Add(new JournalEntryLine
            {
                LineNum     = lineNum++,
                AccountCode = gl.VendorDeposit!,
                AccountName = "Vendor Deposit",
                CardCode    = payment.CardCode,
                CardName    = payment.CardName,
                Debit       = advance,
                Credit      = 0,
                DebitLC     = advance,
                CreditLC    = 0,
                LineMemo    = $"Advance to vendor — {payment.DocNum}",
                CreatedAt   = DateTime.UtcNow,
                InActive    = false,
            });
        }

        // CR: Cash / Bank (real cash disbursed)
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = cashCode!,
            AccountName = payment.PaymentMethod == "Cash" ? "Cash" : "Bank",
            Debit       = 0,
            Credit      = cashOut,
            DebitLC     = 0,
            CreditLC    = cashOut,
            LineMemo    = $"Disbursement — {payment.DocNum}",
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        // CR: Purchase Discount (early-payment discount taken)
        if (totalDiscount > 0)
        {
            je.Lines.Add(new JournalEntryLine
            {
                LineNum     = lineNum++,
                AccountCode = gl.PurchaseDiscount!,
                AccountName = "Purchase Discount",
                Debit       = 0,
                Credit      = totalDiscount,
                DebitLC     = 0,
                CreditLC    = totalDiscount,
                LineMemo    = $"Discount taken — {payment.DocNum}",
                CreatedAt   = DateTime.UtcNow,
                InActive    = false,
            });
        }

        // CR: Withholding Tax Payable (retained, owed to the tax authority)
        if (totalWht > 0)
        {
            je.Lines.Add(new JournalEntryLine
            {
                LineNum     = lineNum++,
                AccountCode = gl.WithholdingTaxPayable!,
                AccountName = "Withholding Tax Payable",
                Debit       = 0,
                Credit      = totalWht,
                DebitLC     = 0,
                CreditLC    = totalWht,
                LineMemo    = $"WHT withheld — {payment.DocNum}",
                CreatedAt   = DateTime.UtcNow,
                InActive    = false,
            });
        }

        var totalDr = je.Lines.Sum(l => l.Debit);
        var totalCr = je.Lines.Sum(l => l.Credit);
        if (Math.Abs(totalDr - totalCr) > 0.01m)
            throw new InvalidOperationException(
                $"Journal entry unbalanced: Dr={totalDr:N2} Cr={totalCr:N2}.");

        je.TotalDebit  = totalDr;
        je.TotalCredit = totalCr;
        je.TotalLC     = totalDr;
        je.TotalFC     = totalDr;

        _db.Set<JournalEntry>().Add(je);
        return je;
    }

    private string GenerateJournalNumber()
    {
        var year   = DateTime.Now.Year;
        var prefix = $"JE-{year}-";

        var last = _db.Set<JournalEntry>()
            .Where(j => j.JrnlNo.StartsWith(prefix))
            .OrderByDescending(j => j.Id)
            .FirstOrDefault();

        if (last == null) return $"{prefix}00001";

        var parts = last.JrnlNo.Split('-');
        if (parts.Length >= 3 && int.TryParse(parts[2], out int lastNum))
            return $"{prefix}{(lastNum + 1):D5}";

        return $"{prefix}00001";
    }
}
