using FarmingApi.Modules.Financials.GLAccountDetermination;
using FarmingApi.Modules.Financials.JournalEntry;
using BPEntity = FarmingApi.Modules.BusinessPartners.BusinessPartnersMaster.BusinessPartnersMaster;

namespace FarmingApi.Modules.SaleAR.ARDownPaymentInvoice;

public interface IARDonwPaymentInvoiceJournalService
{
    JournalEntry CreateJournalEntry(ARDownPaymentInvoice downPaymentInvoice, BPEntity customer);
}

public class ARDonwPaymentInvoiceJournalService : IARDonwPaymentInvoiceJournalService
{
    private readonly MyDbContext _db;

    public ARDonwPaymentInvoiceJournalService(MyDbContext db)
    {
        _db = db;
    }

    public JournalEntry CreateJournalEntry(ARDownPaymentInvoice downPaymentInvoice, BPEntity customer)
    {
        var gl = _db.Set<GLAccountDetermination>().FirstOrDefault()
                 ?? throw new InvalidOperationException(
                     "GL Account Determination (KGLD) not configured. " +
                     "Go to Administration → GL Account Determination and add " +
                     "ARControlAccount, RevenueAccount, TaxOutputAccount.");

        // Prefer the BP-level AR control account, fall back to the global default.
        var arCode = !string.IsNullOrWhiteSpace(customer.ARControlAccount)
            ? customer.ARControlAccount
            : gl.ARControlAccount;

        var revenueCode = gl.RevenueAccount;
        var taxCode = gl.TaxOutputAccount;

        if (string.IsNullOrWhiteSpace(arCode))
            throw new InvalidOperationException(
                "AR Control Account not set — configure it in KGLD or on the Business Partner.");
        if (string.IsNullOrWhiteSpace(revenueCode))
            throw new InvalidOperationException(
                "Revenue Account not set in GL Account Determination (KGLD).");

        var grandTotal = downPaymentInvoice.Total;
        var taxAmount  = downPaymentInvoice.TaxAmount;
        var netRevenue = grandTotal - taxAmount;

        if (grandTotal <= 0)
            throw new InvalidOperationException(
                $"Cannot post AR Down Payment {downPaymentInvoice.DocNum}: total is {grandTotal}");

        var postingDate = downPaymentInvoice.PostingDate ?? DateTime.UtcNow;

        var je = new JournalEntry
        {
            JrnlNo          = GenerateJournalNumber(),
            TransDate       = postingDate,
            DueDate         = downPaymentInvoice.DueDate ?? postingDate,
            DocDate         = postingDate,
            RefNo           = downPaymentInvoice.DocNum,
            Memo            = $"AR Down Payment Invoice {downPaymentInvoice.DocNum} - {customer.CardName}",
            TransType       = "ADPI",
            BaseDocEntry    = downPaymentInvoice.Id,
            BaseDocType     = "KADI",
            Currency        = "USD",
            ExchangeRate    = 1,
            TotalDebit      = 0,
            TotalCredit     = 0,
            TotalFC         = 0,
            TotalLC         = 0,
            Status          = "O",
            IsAutoGenerated = true,
            VersionNum      = 1,
            CreatedAt       = DateTime.UtcNow,
            InActive        = false,
        };

        int lineNum = 1;

        // Dr Accounts Receivable — the full amount the customer owes (incl. tax)
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = arCode,
            AccountName = "Accounts Receivable",
            CardCode    = customer.Code,
            CardName    = customer.CardName,
            Debit       = grandTotal,
            Credit      = 0,
            DebitLC     = grandTotal,
            CreditLC    = 0,
            DebitFC     = 0,
            CreditFC    = 0,
            LineMemo    = $"Accounts Receivable — {downPaymentInvoice.DocNum}",
            TaxAmount   = 0,
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        // Cr Sales Revenue — net of tax
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = revenueCode,
            AccountName = "Sales Revenue",
            CardCode    = null,
            CardName    = null,
            Debit       = 0,
            Credit      = netRevenue,
            DebitLC     = 0,
            CreditLC    = netRevenue,
            DebitFC     = 0,
            CreditFC    = 0,
            LineMemo    = $"Revenue — {downPaymentInvoice.DocNum}",
            TaxAmount   = 0,
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        // Cr Output VAT — only when there is tax
        if (taxAmount > 0)
        {
            if (string.IsNullOrWhiteSpace(taxCode))
                throw new InvalidOperationException(
                    "Invoice has tax but Tax Output Account is not set in KGLD.");

            je.Lines.Add(new JournalEntryLine
            {
                LineNum     = lineNum++,
                AccountCode = taxCode,
                AccountName = "Output VAT",
                CardCode    = null,
                CardName    = null,
                Debit       = 0,
                Credit      = taxAmount,
                DebitLC     = 0,
                CreditLC    = taxAmount,
                DebitFC     = 0,
                CreditFC    = 0,
                LineMemo    = $"Output VAT — {downPaymentInvoice.DocNum}",
                TaxAmount   = taxAmount,
                CreatedAt   = DateTime.UtcNow,
                InActive    = false,
            });
        }

        var totalDr = je.Lines.Sum(l => l.Debit);
        var totalCr = je.Lines.Sum(l => l.Credit);
        if (Math.Abs(totalDr - totalCr) > 0.01m)
            throw new InvalidOperationException(
                $"Journal entry unbalanced: Dr={totalDr:N2} Cr={totalCr:N2}. " +
                $"Check invoice Total ({grandTotal}) vs TaxAmount ({taxAmount}).");

        je.TotalDebit  = totalDr;
        je.TotalCredit = totalCr;
        je.TotalLC     = totalDr;
        je.TotalFC     = 0;

        _db.Set<JournalEntry>().Add(je);
        return je;
    }

    private string GenerateJournalNumber()
    {
        var year   = DateTime.Now.Year;
        var prefix = $"JE-{year}-";

        var last = _db.Set<JournalEntry>()
            .Where(j => j.JrnlNo.StartsWith(prefix))
            .OrderByDescending(j => j.Id)
            .FirstOrDefault();

        if (last == null)
            return $"{prefix}00001";

        var parts = last.JrnlNo.Split('-');
        if (parts.Length >= 3 && int.TryParse(parts[2], out int lastNum))
            return $"{prefix}{(lastNum + 1):D5}";

        return $"{prefix}00001";
    }
}
