using FarmingApi.Modules.Financials.GLAccountDetermination;
using FarmingApi.Modules.Financials.JournalEntry;
using BPEntity = FarmingApi.Modules.BusinessPartners.BusinessPartnersMaster.BusinessPartnersMaster;

namespace FarmingApi.Modules.Banking.IncomingPayment;

// ═══════════════════════════════════════════════════════════════════
// INCOMING PAYMENT JOURNAL SERVICE
// Auto-creates a Journal Entry when an Incoming Payment is created.
//
//   DR  Cash / Bank            DocTotal   (money received)
//   CR  Accounts Receivable    DocTotal   (customer debt settled)
//
// Uses MyDbContext directly so it participates in the SAME transaction
// as the payment save. Caller commits.
// ═══════════════════════════════════════════════════════════════════
public interface IIncomingPaymentJournalService
{
    JournalEntry CreateJournalEntry(IncomingPayment payment, BPEntity? customer);
}

public class IncomingPaymentJournalService : IIncomingPaymentJournalService
{
    private readonly MyDbContext _db;

    public IncomingPaymentJournalService(MyDbContext db) => _db = db;

    public JournalEntry CreateJournalEntry(IncomingPayment payment, BPEntity? customer)
    {
        var gl = _db.Set<GLAccountDetermination>().FirstOrDefault()
            ?? throw new InvalidOperationException(
                "GL Account Determination (KGLD) is not configured. " +
                "Set a Cash/Bank account and an AR Control account first.");

        // ── Debit account: the Payment Means GL, else Cash/Bank from KGLD ──
        var cashCode = !string.IsNullOrWhiteSpace(payment.BankAccount)
            ? payment.BankAccount
            : (payment.PaymentMethod == "Cash" ? gl.CashAccount : gl.BankAccount)
              ?? gl.CashAccount ?? gl.BankAccount;

        // ── Credit account: BP AR override → KGLD AR control → AR ──
        var arCode = !string.IsNullOrWhiteSpace(customer?.ARControlAccount)
            ? customer!.ARControlAccount
            : (gl.ARControlAccount ?? gl.AccountsReceivable);

        if (string.IsNullOrWhiteSpace(cashCode))
            throw new InvalidOperationException(
                "No Cash/Bank account resolved — set the payment's account or the " +
                "Cash/Bank account in GL Account Determination (KGLD).");
        if (string.IsNullOrWhiteSpace(arCode))
            throw new InvalidOperationException(
                "No Accounts Receivable account — set it in KGLD or on the Business Partner.");

        var amount = payment.DocTotal;
        if (amount <= 0)
            throw new InvalidOperationException(
                $"Cannot post payment {payment.DocNum}: amount is {amount}.");

        var je = new JournalEntry
        {
            JrnlNo          = GenerateJournalNumber(),
            TransDate       = payment.DocDate,
            DueDate         = payment.DueDate,
            DocDate         = payment.DocDate,
            RefNo           = payment.DocNum,
            Memo            = $"Incoming Payment {payment.DocNum} — {payment.CardName}",
            TransType       = "KPYI",
            BaseDocType     = "KPYI",
            Currency        = payment.Currency,
            ExchangeRate    = payment.ExchangeRate,
            Status          = "O",
            IsAutoGenerated = true,
            VersionNum      = 1,
            CreatedAt       = DateTime.UtcNow,
            InActive        = false,
        };

        int lineNum = 1;

        // DR: Cash / Bank
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = cashCode!,
            AccountName = payment.PaymentMethod == "Cash" ? "Cash" : "Bank",
            Debit       = amount,
            Credit      = 0,
            DebitLC     = amount,
            CreditLC    = 0,
            LineMemo    = $"Receipt — {payment.DocNum}",
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        // CR: Accounts Receivable
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = arCode!,
            AccountName = "Accounts Receivable",
            CardCode    = payment.CardCode,
            CardName    = payment.CardName,
            Debit       = 0,
            Credit      = amount,
            DebitLC     = 0,
            CreditLC    = amount,
            LineMemo    = $"AR settled — {payment.CardCode} {payment.CardName}",
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        var totalDr = je.Lines.Sum(l => l.Debit);
        var totalCr = je.Lines.Sum(l => l.Credit);
        if (Math.Abs(totalDr - totalCr) > 0.01m)
            throw new InvalidOperationException(
                $"Journal entry unbalanced: Dr={totalDr:N2} Cr={totalCr:N2}.");

        je.TotalDebit  = totalDr;
        je.TotalCredit = totalCr;
        je.TotalLC     = totalDr;
        je.TotalFC     = totalDr;

        _db.Set<JournalEntry>().Add(je);
        return je;
    }

    private string GenerateJournalNumber()
    {
        var year   = DateTime.Now.Year;
        var prefix = $"JE-{year}-";

        var last = _db.Set<JournalEntry>()
            .Where(j => j.JrnlNo.StartsWith(prefix))
            .OrderByDescending(j => j.Id)
            .FirstOrDefault();

        if (last == null) return $"{prefix}00001";

        var parts = last.JrnlNo.Split('-');
        if (parts.Length >= 3 && int.TryParse(parts[2], out int lastNum))
            return $"{prefix}{(lastNum + 1):D5}";

        return $"{prefix}00001";
    }
}
