using FarmingApi.Modules.Financials.GLAccountDetermination;
using FarmingApi.Modules.Financials.JournalEntry;
using BPEntity = FarmingApi.Modules.BusinessPartners.BusinessPartnersMaster.BusinessPartnersMaster;

namespace FarmingApi.Modules.PurchaseAP.APReserveInvoice;

public interface IAPReserveInvoiceJournalService
{
    JournalEntry CreateJournalEntry(APReserveInvoice reserveInvoice, BPEntity vendor);
}

public class APReserveInvoiceJournalService : IAPReserveInvoiceJournalService
{
    private readonly MyDbContext _db;

    public APReserveInvoiceJournalService(MyDbContext db)
    {
        _db = db;
    }

    public JournalEntry CreateJournalEntry(APReserveInvoice reserveInvoice, BPEntity vendor)
    {
        var gl = _db.Set<GLAccountDetermination>().FirstOrDefault()
                 ?? throw new InvalidOperationException(
                     "GL Account Determination (KGLD) not configured. " +
                     "Go to Administration → GL Account Determination and add " +
                     "AccountsPayable, PurchaseExpense, PurchaseTax.");

        var payableCode = gl.AccountsPayable;
        var expenseCode = gl.PurchaseExpense;
        var taxCode     = gl.PurchaseTax;

        if (string.IsNullOrWhiteSpace(payableCode))
            throw new InvalidOperationException(
                "Accounts Payable account not set in GL Account Determination (KGLD).");
        if (string.IsNullOrWhiteSpace(expenseCode))
            throw new InvalidOperationException(
                "Purchase Expense account not set in GL Account Determination (KGLD).");

        var grandTotal = reserveInvoice.Total;
        var taxAmount  = reserveInvoice.TaxAmount;
        var netExpense = grandTotal - taxAmount;

        if (grandTotal <= 0)
            throw new InvalidOperationException(
                $"Cannot post AP Reserve Invoice {reserveInvoice.DocNum}: total is {grandTotal}");

        var postingDate = reserveInvoice.PostingDate ?? DateTime.UtcNow;

        var je = new JournalEntry
        {
            JrnlNo          = GenerateJournalNumber(),
            TransDate       = postingDate,
            DueDate         = reserveInvoice.DueDate ?? postingDate,
            DocDate         = postingDate,
            RefNo           = reserveInvoice.DocNum,
            Memo            = $"AP Reserve Invoice {reserveInvoice.DocNum} - {vendor.CardName}",
            TransType       = "APRI",
            BaseDocEntry    = reserveInvoice.Id,
            BaseDocType     = "KPRI",
            Currency        = "USD",
            ExchangeRate    = 1,
            TotalDebit      = 0,
            TotalCredit     = 0,
            TotalFC         = 0,
            TotalLC         = 0,
            Status          = "O",
            IsAutoGenerated = true,
            VersionNum      = 1,
            CreatedAt       = DateTime.UtcNow,
            InActive        = false,
        };

        int lineNum = 1;

        // An AP reserve invoice records a purchase and the payable owed to the vendor.
        // Dr Purchase Expense — net of tax
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = expenseCode,
            AccountName = "Purchase Expense",
            CardCode    = null,
            CardName    = null,
            Debit       = netExpense,
            Credit      = 0,
            DebitLC     = netExpense,
            CreditLC    = 0,
            DebitFC     = 0,
            CreditFC    = 0,
            LineMemo    = $"Purchase — {reserveInvoice.DocNum}",
            TaxAmount   = 0,
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        // Dr Input VAT — recoverable tax, only when there is tax
        if (taxAmount > 0)
        {
            if (string.IsNullOrWhiteSpace(taxCode))
                throw new InvalidOperationException(
                    "Invoice has tax but Purchase Tax (input VAT) account is not set in KGLD.");

            je.Lines.Add(new JournalEntryLine
            {
                LineNum     = lineNum++,
                AccountCode = taxCode,
                AccountName = "Input VAT",
                CardCode    = null,
                CardName    = null,
                Debit       = taxAmount,
                Credit      = 0,
                DebitLC     = taxAmount,
                CreditLC    = 0,
                DebitFC     = 0,
                CreditFC    = 0,
                LineMemo    = $"Input VAT — {reserveInvoice.DocNum}",
                TaxAmount   = taxAmount,
                CreatedAt   = DateTime.UtcNow,
                InActive    = false,
            });
        }

        // Cr Accounts Payable — full amount owed to the vendor (incl. tax)
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = payableCode,
            AccountName = "Accounts Payable",
            CardCode    = vendor.Code,
            CardName    = vendor.CardName,
            Debit       = 0,
            Credit      = grandTotal,
            DebitLC     = 0,
            CreditLC    = grandTotal,
            DebitFC     = 0,
            CreditFC    = 0,
            LineMemo    = $"Accounts Payable — {reserveInvoice.DocNum}",
            TaxAmount   = 0,
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        var totalDr = je.Lines.Sum(l => l.Debit);
        var totalCr = je.Lines.Sum(l => l.Credit);
        if (Math.Abs(totalDr - totalCr) > 0.01m)
            throw new InvalidOperationException(
                $"Journal entry unbalanced: Dr={totalDr:N2} Cr={totalCr:N2}. " +
                $"Check invoice Total ({grandTotal}) vs TaxAmount ({taxAmount}).");

        je.TotalDebit  = totalDr;
        je.TotalCredit = totalCr;
        je.TotalLC     = totalDr;
        je.TotalFC     = 0;

        _db.Set<JournalEntry>().Add(je);
        return je;
    }

    private string GenerateJournalNumber()
    {
        var year   = DateTime.Now.Year;
        var prefix = $"JE-{year}-";

        var last = _db.Set<JournalEntry>()
            .Where(j => j.JrnlNo.StartsWith(prefix))
            .OrderByDescending(j => j.Id)
            .FirstOrDefault();

        if (last == null)
            return $"{prefix}00001";

        var parts = last.JrnlNo.Split('-');
        if (parts.Length >= 3 && int.TryParse(parts[2], out int lastNum))
            return $"{prefix}{(lastNum + 1):D5}";

        return $"{prefix}00001";
    }
}
