using FarmingApi.Modules.Financials.GLAccountDetermination;
using FarmingApi.Modules.Financials.JournalEntry;

using BPEntity = FarmingApi.Modules.BusinessPartners.BusinessPartnersMaster.BusinessPartnersMaster;

namespace FarmingApi.Modules.SaleAR.ARInvoice;

// ═══════════════════════════════════════════════════════════════════
// AR INVOICE JOURNAL SERVICE
// Auto-creates a Journal Entry when an AR Invoice is created.
//
//   DR  Accounts Receivable    Total (incl. tax)
//   CR  Sales Revenue          Total - TaxAmount
//   CR  Output VAT             TaxAmount (only if > 0)
//
// Uses MyDbContext directly (not repository) so it participates
// in the SAME transaction as the AR Invoice save.
// ═══════════════════════════════════════════════════════════════════

public interface IARInvoiceJournalService
{
    /// <summary>
    /// Creates a JournalEntry + Lines in the DbContext (without calling SaveChanges).
    /// The caller is responsible for committing the transaction.
    /// Returns the JournalEntry entity (Id populated after SaveChanges).
    /// </summary>
    JournalEntry CreateJournalEntry(ARInvoice invoice, BPEntity customer);
}

public class ARInvoiceJournalService : IARInvoiceJournalService
{
    private readonly MyDbContext _db;

    public ARInvoiceJournalService(MyDbContext db)
    {
        _db = db;
    }

    public JournalEntry CreateJournalEntry(ARInvoice invoice, BPEntity customer)
    {
        // ── 1. Load KGLD row ──────────────────────────────────────
        var gl = _db.Set<GLAccountDetermination>().FirstOrDefault()
            ?? throw new InvalidOperationException(
                "GL Account Determination (KGLD) not configured. " +
                "Go to Administration → GL Account Determination and add " +
                "ARControlAccount, RevenueAccount, TaxOutputAccount.");

        // ── 2. Resolve account codes (BP override → KGLD default) ─
        var arCode = !string.IsNullOrWhiteSpace(customer.ARControlAccount)
            ? customer.ARControlAccount
            : gl.ARControlAccount;

        var revenueCode = gl.RevenueAccount;
        var taxCode     = gl.TaxOutputAccount;

        if (string.IsNullOrWhiteSpace(arCode))
            throw new InvalidOperationException(
                "AR Control Account not set — configure it in KGLD or on the Business Partner.");
        if (string.IsNullOrWhiteSpace(revenueCode))
            throw new InvalidOperationException(
                "Revenue Account not set in GL Account Determination (KGLD).");

        // ── 3. Amounts ────────────────────────────────────────────
        var grandTotal = invoice.Total;
        var taxAmount  = invoice.TaxAmount;
        var netRevenue = grandTotal - taxAmount;

        if (grandTotal <= 0)
            throw new InvalidOperationException(
                $"Cannot post AR Invoice {invoice.DocNum}: total is {grandTotal}.");

        // ── 4. Build JE header ────────────────────────────────────
        var postingDate = invoice.PostingDate ?? DateTime.UtcNow;

        var je = new JournalEntry
        {
            JrnlNo          = GenerateJournalNumber(),
            TransDate       = postingDate,
            DueDate         = invoice.DueDate ?? postingDate,
            DocDate         = postingDate,
            RefNo           = invoice.DocNum,
            Memo            = $"AR Invoice {invoice.DocNum} — {customer.CardName}",
            TransType       = "AR",
            BaseDocEntry    = invoice.Id,   // populated after invoice SaveChanges
            BaseDocType     = "KARI",
            Currency        = "USD",
            ExchangeRate    = 1,
            TotalDebit      = 0,
            TotalCredit     = 0,
            TotalLC         = 0,
            TotalFC         = 0,
            Status          = "O",
            IsAutoGenerated = true,
            VersionNum      = 1,
            CreatedAt       = DateTime.UtcNow,
            InActive        = false,
        };

        int lineNum = 1;

        // ── 5. DR: Accounts Receivable (full incl. tax) ───────────
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = arCode,
            AccountName = "Accounts Receivable",
            CardCode    = customer.Code,
            CardName    = customer.CardName,
            Debit       = grandTotal,
            Credit      = 0,
            DebitLC     = grandTotal,
            CreditLC    = 0,
            DebitFC     = 0,
            CreditFC    = 0,
            LineMemo    = $"AR — {customer.Code} {customer.CardName}",
            TaxAmount   = 0,
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        // ── 6. CR: Sales Revenue (net excl. tax) ──────────────────
        je.Lines.Add(new JournalEntryLine
        {
            LineNum     = lineNum++,
            AccountCode = revenueCode,
            AccountName = "Sales Revenue",
            CardCode    = null,
            CardName    = null,
            Debit       = 0,
            Credit      = netRevenue,
            DebitLC     = 0,
            CreditLC    = netRevenue,
            DebitFC     = 0,
            CreditFC    = 0,
            LineMemo    = $"Revenue — {invoice.DocNum}",
            TaxAmount   = 0,
            CreatedAt   = DateTime.UtcNow,
            InActive    = false,
        });

        // ── 7. CR: Output VAT (only when tax > 0) ────────────────
        if (taxAmount > 0)
        {
            if (string.IsNullOrWhiteSpace(taxCode))
                throw new InvalidOperationException(
                    "Invoice has tax but Tax Output Account is not set in KGLD.");

            je.Lines.Add(new JournalEntryLine
            {
                LineNum     = lineNum++,
                AccountCode = taxCode,
                AccountName = "Output VAT",
                CardCode    = null,
                CardName    = null,
                Debit       = 0,
                Credit      = taxAmount,
                DebitLC     = 0,
                CreditLC    = taxAmount,
                DebitFC     = 0,
                CreditFC    = 0,
                LineMemo    = $"Output VAT — {invoice.DocNum}",
                TaxAmount   = taxAmount,
                CreatedAt   = DateTime.UtcNow,
                InActive    = false,
            });
        }

        // ── 8. Balance check + totals ─────────────────────────────
        var totalDr = je.Lines.Sum(l => l.Debit);
        var totalCr = je.Lines.Sum(l => l.Credit);

        if (Math.Abs(totalDr - totalCr) > 0.01m)
            throw new InvalidOperationException(
                $"Journal entry unbalanced: Dr={totalDr:N2} Cr={totalCr:N2}. " +
                $"Check invoice Total ({grandTotal}) vs TaxAmount ({taxAmount}).");

        je.TotalDebit  = totalDr;
        je.TotalCredit = totalCr;
        je.TotalLC     = totalDr;
        je.TotalFC     = totalDr;

        // ── 9. Add to DbContext (NOT SaveChanges — caller does that)
        _db.Set<JournalEntry>().Add(je);

        return je;
    }

    // ── Generate JE number: JE-2026-00001 ─────────────────────────
    private string GenerateJournalNumber()
    {
        var year   = DateTime.Now.Year;
        var prefix = $"JE-{year}-";

        var last = _db.Set<JournalEntry>()
            .Where(j => j.JrnlNo.StartsWith(prefix))
            .OrderByDescending(j => j.Id)
            .FirstOrDefault();

        if (last == null)
            return $"{prefix}00001";

        var parts = last.JrnlNo.Split('-');
        if (parts.Length >= 3 && int.TryParse(parts[2], out int lastNum))
            return $"{prefix}{(lastNum + 1):D5}";

        return $"{prefix}00001";
    }
}